/**
 * Do not edit directly, this file was auto-generated.
 */

export const WDS_COLOR_BACKGROUND_DEFAULT_PRIMARY = '#164e63'; // Bg/Default/Default
export const WDS_COLOR_BACKGROUND_DEFAULT_SECONDARY = '#164e63'; // Bg/Default/Secondary
export const WDS_COLOR_BACKGROUND_DEFAULT_TERTIARY = '#155e75'; // Bg/Default/Tertiary
export const WDS_COLOR_BACKGROUND_DEFAULT_PRIMARY_HOVER = '#164e63'; // Bg/Default/Default Hover
export const WDS_COLOR_BACKGROUND_DEFAULT_SECONDARY_HOVER = '#155e75'; // Bg/Default/Secondary Hover
export const WDS_COLOR_BACKGROUND_DEFAULT_TERTIARY_HOVER = '#0e7490'; // Bg/Default/Tertiary Hover
export const WDS_COLOR_BACKGROUND_BRAND_DEFAULT = '#06b6d4'; // Bg/Brand/Default
export const WDS_COLOR_BACKGROUND_BRAND_SECONDARY = '#0891b2'; // Bg/Brand/Secondary
export const WDS_COLOR_BACKGROUND_BRAND_HOVER = '#06b6d4'; // Bg/Brand/Hover
export const WDS_COLOR_BACKGROUND_BRAND_SECONDARY_HOVER = '#0e7490'; // Bg/Brand/Secondary Hover
export const WDS_COLOR_BACKGROUND_BRAND_TERTIARY = '#0e7490'; // Bg/Brand/Tertiary
export const WDS_COLOR_BACKGROUND_BRAND_TERTIARY_HOVER = '#155e75'; // Bg/Brand/Tertiary Hover
export const WDS_COLOR_BACKGROUND_POSITIVE_DEFAULT = '#008043'; // Bg/Positive/Default
export const WDS_COLOR_BACKGROUND_POSITIVE_SECONDARY = '#02542d'; // Bg/Positive/Secondary
export const WDS_COLOR_BACKGROUND_POSITIVE_HOVER = '#02542d'; // Bg/Positive/Hover
export const WDS_COLOR_BACKGROUND_POSITIVE_SECONDARY_HOVER = '#024023'; // Bg/Positive/Secondary Hover
export const WDS_COLOR_BACKGROUND_POSITIVE_TERTIARY = '#024023'; // Bg/Positive/Tertiary
export const WDS_COLOR_BACKGROUND_POSITIVE_TERTIARY_HOVER = '#062d1b'; // Bg/Positive/Tertiary Hover
export const WDS_COLOR_BACKGROUND_WARNING_DEFAULT = '#e8b931'; // Bg/Warning/Default
export const WDS_COLOR_BACKGROUND_WARNING_SECONDARY = '#e5a000'; // Bg/Warning/Secondary
export const WDS_COLOR_BACKGROUND_WARNING_HOVER = '#e5a000'; // Bg/Warning/Hover
export const WDS_COLOR_BACKGROUND_WARNING_SECONDARY_HOVER = '#bf6a02'; // Bg/Warning/Secondary Hover
export const WDS_COLOR_BACKGROUND_WARNING_TERTIARY = '#bf6a02'; // Bg/Warning/Tertiary
export const WDS_COLOR_BACKGROUND_WARNING_TERTIARY_HOVER = '#975102'; // Bg/Warning/Tertiary Hover
export const WDS_COLOR_BACKGROUND_DANGER_DEFAULT = '#f03330'; // Bg/Danger/Default
export const WDS_COLOR_BACKGROUND_DANGER_SECONDARY = '#9c120f'; // Bg/Danger/Secondary
export const WDS_COLOR_BACKGROUND_DANGER_HOVER = '#d21e1e'; // Bg/Danger/Hover
export const WDS_COLOR_BACKGROUND_DANGER_SECONDARY_HOVER = '#690807'; // Bg/Danger/Secondary Hover
export const WDS_COLOR_BACKGROUND_DANGER_TERTIARY = '#4d0b0a'; // Bg/Danger/Tertiary
export const WDS_COLOR_BACKGROUND_DANGER_TERTIARY_HOVER = '#300603'; // Bg/Danger/Tertiary Hover
export const WDS_COLOR_BACKGROUND_DISABLED_DEFAULT = '#757575'; // Bg/Disabled/Default
export const WDS_COLOR_BACKGROUND_UTILITIES_SCRIM = '#000000'; // Bg/Utilities/Scrim
export const WDS_COLOR_BACKGROUND_UTILITIES_OVERLAY = '#000000'; // Bg/Utilities/Overlay
export const WDS_COLOR_BACKGROUND_UTILITIES_BLANKET = '#000000'; // Bg/Utilities/Blanket
export const WDS_COLOR_BACKGROUND_UTILITIES_MEASUREMENT = '#9d174d'; // Bg/Utilities/Measurement
export const WDS_COLOR_BACKGROUND_UTILITIES_HIGHLIGHT = '#ffffff';
export const WDS_COLOR_BACKGROUND_UTILITIES_HIGHLIGHT_2 = '#ffffff';
export const WDS_COLOR_BACKGROUND_UTILITIES_HIGHLIGHT_BRAND = '#87a5ff';
export const WDS_COLOR_BACKGROUND_UTILITIES_HIGHLIGHT_BRAND_2 = '#456eeb';
export const WDS_COLOR_BACKGROUND_UTILITIES_HIGHLIGHT_BRAND_3 = '#456eeb';
export const WDS_COLOR_BACKGROUND_UTILITIES_HIGHLIGHT_BRAND_4 = '#456eeb';
export const WDS_COLOR_BACKGROUND_NEUTRAL_DEFAULT = '#b2b2b2'; // Bg/Neutral/Default
export const WDS_COLOR_BACKGROUND_NEUTRAL_HOVER = '#949494'; // Bg/Neutral/Hover
export const WDS_COLOR_BACKGROUND_NEUTRAL_SECONDARY = '#767676'; // Bg/Neutral/Secondary
export const WDS_COLOR_BACKGROUND_NEUTRAL_SECONDARY_HOVER = '#5a5a5a'; // Bg/Neutral/Secondary Hover
export const WDS_COLOR_BACKGROUND_NEUTRAL_TERTIARY = '#434343'; // Bg/Neutral/Tertiary
export const WDS_COLOR_BACKGROUND_NEUTRAL_TERTIARY_HOVER = '#303030'; // Bg/Neutral/Tertiary Hover
export const WDS_COLOR_BACKGROUND_NEUTRAL_SECONDARY_2 = '#767676'; // Bg/Neutral/Secondary
export const WDS_COLOR_BACKGROUND_BOLD_DEFAULT = '#0c0c0d'; // Bg/Default/Default
export const WDS_COLOR_BACKGROUND_BOLD_DEFAULT_HOVER = '#1e1e1e'; // Bg/Default/Default Hover
export const WDS_COLOR_BACKGROUND_BOLD_SECONDARY = '#1e1e1e'; // Bg/Default/Secondary
export const WDS_COLOR_BACKGROUND_BOLD_SECONDARY_HOVER = '#111111'; // Bg/Default/Secondary Hover
export const WDS_COLOR_BACKGROUND_BOLD_TERTIARY = '#383838'; // Bg/Default/Tertiary
export const WDS_COLOR_BACKGROUND_BOLD_TERTIARY_HOVER = '#2c2c2c'; // Bg/Default/Tertiary Hover
export const WDS_COLOR_BACKGROUND_BOLD_TRANSPARENT = '#0c0c0d'; // Bg/Default/Tertiary Hover
export const WDS_COLOR_BACKGROUND_ACCENT_DEFAULT = '#14b8a6'; // Bg/Brand/Default
export const WDS_COLOR_BACKGROUND_ACCENT_HOVER = '#0d9488'; // Bg/Brand/Hover
export const WDS_COLOR_BACKGROUND_ACCENT_SECONDARY = '#0d9488'; // Bg/Brand/Secondary
export const WDS_COLOR_BACKGROUND_ACCENT_SECONDARY_HOVER = '#0f766e'; // Bg/Brand/Secondary Hover
export const WDS_COLOR_BACKGROUND_ACCENT_TERTIARY = '#115e59'; // Bg/Brand/Tertiary
export const WDS_COLOR_BACKGROUND_ACCENT_TERTIARY_HOVER = '#134e4a'; // Bg/Brand/Tertiary Hover
export const WDS_COLOR_BACKGROUND_INVERT_DEFAULT = '#ecfeff'; // Bg/Default/Default
export const WDS_COLOR_BACKGROUND_INVERT_DEFAULT_HOVER = '#a5f3fc'; // Bg/Default/Default Hover
export const WDS_COLOR_BACKGROUND_INVERT_SECONDARY = '#a5f3fc'; // Bg/Default/Secondary
export const WDS_COLOR_BACKGROUND_INVERT_SECONDARY_HOVER = '#67e8f9'; // Bg/Default/Secondary Hover
export const WDS_COLOR_BACKGROUND_INVERT_TERTIARY = '#67e8f9'; // Bg/Default/Tertiary
export const WDS_COLOR_BACKGROUND_INVERT_TERTIARY_HOVER = '#06b6d4'; // Bg/Default/Tertiary Hover
export const WDS_COLOR_TEXT_DEFAULT_PRIMARY = '#ffffff';
export const WDS_COLOR_TEXT_DEFAULT_SECONDARY = '#ffffff';
export const WDS_COLOR_TEXT_DEFAULT_TERTIARY = '#ffffff';
export const WDS_COLOR_TEXT_BRAND_DEFAULT = '#cffafe';
export const WDS_COLOR_TEXT_BRAND_SECONDARY = '#67e8f9';
export const WDS_COLOR_TEXT_BRAND_TERTIARY = '#06b6d4';
export const WDS_COLOR_TEXT_BRAND_ON_BRAND = '#164e63';
export const WDS_COLOR_TEXT_BRAND_ON_BRAND_SECONDARY = '#cffafe';
export const WDS_COLOR_TEXT_BRAND_ON_BRAND_TERTIARY = '#a5f3fc';
export const WDS_COLOR_TEXT_POSITIVE_DEFAULT = '#aff4c6';
export const WDS_COLOR_TEXT_POSITIVE_SECONDARY = '#85e0a3';
export const WDS_COLOR_TEXT_POSITIVE_TERTIARY = '#009951';
export const WDS_COLOR_TEXT_POSITIVE_ON_POSITIVE = '#ebffee';
export const WDS_COLOR_TEXT_POSITIVE_ON_POSITIVE_SECONDARY = '#ebffee';
export const WDS_COLOR_TEXT_POSITIVE_ON_POSITIVE_TERTIARY = '#ebffee';
export const WDS_COLOR_TEXT_WARNING_DEFAULT = '#fff1c2';
export const WDS_COLOR_TEXT_WARNING_SECONDARY = '#e8b931';
export const WDS_COLOR_TEXT_WARNING_TERTIARY = '#bf6a02';
export const WDS_COLOR_TEXT_WARNING_ON_WARNING = '#401b01';
export const WDS_COLOR_TEXT_WARNING_ON_WARNING_SECONDARY = '#fff1c2';
export const WDS_COLOR_TEXT_WARNING_ON_WARNING_TERTIARY = '#fffbeb';
export const WDS_COLOR_TEXT_DANGER_DEFAULT = '#fcb3ad';
export const WDS_COLOR_TEXT_DANGER_SECONDARY = '#ff7d6f';
export const WDS_COLOR_TEXT_DANGER_TERTIARY = '#f03330';
export const WDS_COLOR_TEXT_DANGER_ON_DANGER = '#fee9e7';
export const WDS_COLOR_TEXT_DANGER_ON_DANGER_SECONDARY = '#fee9e7';
export const WDS_COLOR_TEXT_DANGER_ON_DANGER_TERTIARY = '#fee9e7';
export const WDS_COLOR_TEXT_DISABLED_DEFAULT = '#d9d9d9';
export const WDS_COLOR_TEXT_DISABLED_ON_DISABLED = '#b3b3b3';
export const WDS_COLOR_TEXT_UTILITIES_TEXT_ON_OVERLAY = '#ffffff';
export const WDS_COLOR_TEXT_UTILITIES_TEXT_ON_MEASUREMENT = '#fbcfe8';
export const WDS_COLOR_TEXT_NEUTRAL_DEFAULT = '#f3f3f3';
export const WDS_COLOR_TEXT_NEUTRAL_SECONDARY = '#e3e3e3';
export const WDS_COLOR_TEXT_NEUTRAL_TERTIARY = '#cdcdcd';
export const WDS_COLOR_TEXT_NEUTRAL_ON_NEUTRAL = '#303030';
export const WDS_COLOR_TEXT_NEUTRAL_ON_NEUTRAL_SECONDARY = '#f3f3f3';
export const WDS_COLOR_TEXT_NEUTRAL_ON_NEUTRAL_TERTIARY = '#f3f3f3';
export const WDS_COLOR_TEXT_INVERT_DEFAULT = '#1e1e1e';
export const WDS_COLOR_TEXT_INVERT_SECONDARY = '#757575';
export const WDS_COLOR_TEXT_INVERT_TERTIARY = '#b3b3b3';
export const WDS_COLOR_ICON_DEFAULT_PRIMARY = '#ffffff';
export const WDS_COLOR_ICON_DEFAULT_SECONDARY = '#ffffff';
export const WDS_COLOR_ICON_DEFAULT_TERTIARY = '#ffffff';
export const WDS_COLOR_ICON_BRAND_DEFAULT = '#cffafe';
export const WDS_COLOR_ICON_BRAND_SECONDARY = '#67e8f9';
export const WDS_COLOR_ICON_BRAND_TERTIARY = '#06b6d4';
export const WDS_COLOR_ICON_BRAND_ON_BRAND = '#164e63';
export const WDS_COLOR_ICON_BRAND_ON_BRAND_SECONDARY = '#cffafe';
export const WDS_COLOR_ICON_BRAND_ON_BRAND_TERTIARY = '#a5f3fc';
export const WDS_COLOR_ICON_POSITIVE_DEFAULT = '#aff4c6';
export const WDS_COLOR_ICON_POSITIVE_SECONDARY = '#85e0a3';
export const WDS_COLOR_ICON_POSITIVE_TERTIARY = '#009951';
export const WDS_COLOR_ICON_POSITIVE_ON_POSITIVE = '#ebffee';
export const WDS_COLOR_ICON_POSITIVE_ON_POSITIVE_SECONDARY = '#ebffee';
export const WDS_COLOR_ICON_POSITIVE_ON_POSITIVE_TERTIARY = '#ebffee';
export const WDS_COLOR_ICON_WARNING_DEFAULT = '#fff1c2';
export const WDS_COLOR_ICON_WARNING_SECONDARY = '#e8b931';
export const WDS_COLOR_ICON_WARNING_TERTIARY = '#bf6a02';
export const WDS_COLOR_ICON_WARNING_ON_WARNING = '#401b01';
export const WDS_COLOR_ICON_WARNING_ON_WARNING_SECONDARY = '#fffbeb';
export const WDS_COLOR_ICON_WARNING_ON_WARNING_TERTIARY = '#fffbeb';
export const WDS_COLOR_ICON_DANGER_DEFAULT = '#fcb3ad';
export const WDS_COLOR_ICON_DANGER_SECONDARY = '#ff7d6f';
export const WDS_COLOR_ICON_DANGER_TERTIARY = '#f03330';
export const WDS_COLOR_ICON_DANGER_ON_DANGER = '#fee9e7';
export const WDS_COLOR_ICON_DANGER_ON_DANGER_SECONDARY = '#fee9e7';
export const WDS_COLOR_ICON_DANGER_ON_DANGER_TERTIARY = '#fee9e7';
export const WDS_COLOR_ICON_DISABLED_DEFAULT = '#d9d9d9';
export const WDS_COLOR_ICON_DISABLED_ON_DISABLED = '#b3b3b3';
export const WDS_COLOR_ICON_NEUTRAL_DEFAULT = '#e3e3e3';
export const WDS_COLOR_ICON_NEUTRAL_SECONDARY = '#cdcdcd';
export const WDS_COLOR_ICON_NEUTRAL_TERTIARY = '#b2b2b2';
export const WDS_COLOR_ICON_NEUTRAL_ON_NEUTRAL = '#303030';
export const WDS_COLOR_ICON_NEUTRAL_ON_NEUTRAL_SECONDARY = '#f3f3f3';
export const WDS_COLOR_ICON_NEUTRAL_ON_NEUTRAL_TERTIARY = '#f3f3f3';
export const WDS_COLOR_ICON_UTILITIES_ICON_ON_MEASUREMENT = '#fbcfe8';
export const WDS_COLOR_ICON_UTILITIES_ICON = '#f472b6';
export const WDS_COLOR_BORDER_DEFAULT_PRIMARY = '#155e75';
export const WDS_COLOR_BORDER_DEFAULT_SECONDARY = '#0e7490';
export const WDS_COLOR_BORDER_DEFAULT_TERTIARY = '#0891b2';
export const WDS_COLOR_BORDER_BRAND_DEFAULT = '#67e8f9';
export const WDS_COLOR_BORDER_BRAND_SECONDARY = '#06b6d4';
export const WDS_COLOR_BORDER_BRAND_TERTIARY = '#06b6d4';
export const WDS_COLOR_BORDER_POSITIVE_DEFAULT = '#85e0a3';
export const WDS_COLOR_BORDER_POSITIVE_SECONDARY = '#14ae5c';
export const WDS_COLOR_BORDER_POSITIVE_TERTIARY = '#009951';
export const WDS_COLOR_BORDER_WARNING_DEFAULT = '#e8b931';
export const WDS_COLOR_BORDER_WARNING_SECONDARY = '#bf6a02';
export const WDS_COLOR_BORDER_WARNING_TERTIARY = '#975102';
export const WDS_COLOR_BORDER_DANGER_DEFAULT = '#fcb3ad';
export const WDS_COLOR_BORDER_DANGER_SECONDARY = '#ff7d6f';
export const WDS_COLOR_BORDER_DANGER_TERTIARY = '#d21e1e';
export const WDS_COLOR_BORDER_DISABLED_DEFAULT = '#b3b3b3';
export const WDS_COLOR_BORDER_UTILITIES_MEASUREMENT = '#db2777';
export const WDS_COLOR_BORDER_UTILITIES_SWATCH = '#ffffff';
export const WDS_COLOR_BORDER_NEUTRAL_DEFAULT = '#f3f3f3';
export const WDS_COLOR_BORDER_NEUTRAL_SECONDARY = '#949494';
export const WDS_COLOR_BORDER_NEUTRAL_TERTIARY = '#767676';
export const WDS_COLOR_OVERLAY_WHITE_WHITE4 = '#ffffff';
export const WDS_MODALS_TOMATO_TOMATO10 = '#ec5e41';
export const WDS_MODALS_TOMATO_TOMATO7 = '#7f2315';
export const WDS_MODALS_TOMATO_TOMATO6 = '#652016';
export const WDS_MODALS_TOMATO_TOMATO5 = '#541c15';
export const WDS_MODALS_TOMATO_TOMATO12 = '#feefec';
export const WDS_MODALS_TOMATO_TOMATO11 = '#f16a50';
export const WDS_MODALS_TOMATO_TOMATO9 = '#e54d2e';
export const WDS_MODALS_TOMATO_TOMATO3 = '#3b1813';
export const WDS_MODALS_TOMATO_TOMATO8 = '#a42a12';
export const WDS_MODALS_TOMATO_TOMATO2 = '#2a1410';
export const WDS_MODALS_TOMATO_TOMATO4 = '#481a14';
export const WDS_MODALS_TOMATO_TOMATO1 = '#1d1412';
export const WDS_MODALS_RED_RED4 = '#481a1d';
export const WDS_MODALS_RED_RED5 = '#541b1f';
export const WDS_MODALS_RED_RED9 = '#e5484d';
export const WDS_MODALS_RED_RED8 = '#aa2429';
export const WDS_MODALS_RED_RED12 = '#feecee';
export const WDS_MODALS_RED_RED6 = '#671e22';
export const WDS_MODALS_RED_RED3 = '#3c181a';
export const WDS_MODALS_RED_RED1 = '#1f1315';
export const WDS_MODALS_RED_RED2 = '#291415';
export const WDS_MODALS_RED_RED7 = '#822025';
export const WDS_MODALS_RED_RED10 = '#f2555a';
export const WDS_MODALS_RED_RED11 = '#ff6369';
export const WDS_MODALS_VIOLET_VIOLET10 = '#7c66dc';
export const WDS_MODALS_VIOLET_VIOLET12 = '#f1eefe';
export const WDS_MODALS_VIOLET_VIOLET9 = '#6e56cf';
export const WDS_MODALS_VIOLET_VIOLET3 = '#251e40';
export const WDS_MODALS_VIOLET_VIOLET4 = '#2c2250';
export const WDS_MODALS_VIOLET_VIOLET8 = '#5842c3';
export const WDS_MODALS_VIOLET_VIOLET1 = '#17151f';
export const WDS_MODALS_VIOLET_VIOLET7 = '#443592';
export const WDS_MODALS_VIOLET_VIOLET6 = '#392c72';
export const WDS_MODALS_VIOLET_VIOLET5 = '#32275f';
export const WDS_MODALS_VIOLET_VIOLET11 = '#9e8cfc';
export const WDS_MODALS_VIOLET_VIOLET2 = '#1c172b';
export const WDS_MODALS_INDIGO_INDIGO10 = '#5373e7';
export const WDS_MODALS_INDIGO_INDIGO8 = '#2f4eb2';
export const WDS_MODALS_INDIGO_INDIGO7 = '#273e89';
export const WDS_MODALS_INDIGO_INDIGO2 = '#15192d';
export const WDS_MODALS_INDIGO_INDIGO9 = '#3e63dd';
export const WDS_MODALS_INDIGO_INDIGO3 = '#192140';
export const WDS_MODALS_INDIGO_INDIGO6 = '#22346e';
export const WDS_MODALS_INDIGO_INDIGO5 = '#1f2c5c';
export const WDS_MODALS_INDIGO_INDIGO12 = '#ffffff';
export const WDS_MODALS_INDIGO_INDIGO4 = '#1c274f';
export const WDS_MODALS_INDIGO_INDIGO11 = '#849dff';
export const WDS_MODALS_INDIGO_INDIGO1 = '#131620';
export const WDS_MODALS_BLUE_BLUE7 = '#0a4481';
export const WDS_MODALS_BLUE_BLUE9 = '#0091ff';
export const WDS_MODALS_BLUE_BLUE6 = '#0d3868';
export const WDS_MODALS_BLUE_BLUE5 = '#0f3058';
export const WDS_MODALS_BLUE_BLUE4 = '#102a4c';
export const WDS_MODALS_BLUE_BLUE10 = '#369eff';
export const WDS_MODALS_BLUE_BLUE8 = '#0954a5';
export const WDS_MODALS_BLUE_BLUE2 = '#0f1b2d';
export const WDS_MODALS_BLUE_BLUE3 = '#10243e';
export const WDS_MODALS_BLUE_BLUE11 = '#52a9ff';
export const WDS_MODALS_BLUE_BLUE12 = '#eaf6ff';
export const WDS_MODALS_BLUE_BLUE1 = '#0f1720';
export const WDS_MODALS_CYAN_CYAN10 = '#00b1cc';
export const WDS_MODALS_CYAN_CYAN8 = '#00647d';
export const WDS_MODALS_CYAN_CYAN7 = '#045063';
export const WDS_MODALS_CYAN_CYAN2 = '#061e24';
export const WDS_MODALS_CYAN_CYAN4 = '#07303b';
export const WDS_MODALS_CYAN_CYAN5 = '#073844';
export const WDS_MODALS_CYAN_CYAN12 = '#e1f8fa';
export const WDS_MODALS_CYAN_CYAN9 = '#05a2c2';
export const WDS_MODALS_CYAN_CYAN3 = '#072830';
export const WDS_MODALS_CYAN_CYAN6 = '#064150';
export const WDS_MODALS_CYAN_CYAN11 = '#00c2d7';
export const WDS_MODALS_CYAN_CYAN1 = '#07191d';
export const WDS_MODALS_TEAL_TEAL9 = '#12a594';
export const WDS_MODALS_TEAL_TEAL7 = '#0b544a';
export const WDS_MODALS_TEAL_TEAL5 = '#083932';
export const WDS_MODALS_TEAL_TEAL4 = '#07312b';
export const WDS_MODALS_TEAL_TEAL10 = '#10b3a3';
export const WDS_MODALS_TEAL_TEAL3 = '#062923';
export const WDS_MODALS_TEAL_TEAL8 = '#0c6d62';
export const WDS_MODALS_TEAL_TEAL6 = '#09443c';
export const WDS_MODALS_TEAL_TEAL1 = '#091915';
export const WDS_MODALS_TEAL_TEAL12 = '#e1faf4';
export const WDS_MODALS_TEAL_TEAL11 = '#0ac5b3';
export const WDS_MODALS_TEAL_TEAL2 = '#04201b';
export const WDS_MODALS_GREEN_GREEN9 = '#30a46c';
export const WDS_MODALS_GREEN_GREEN10 = '#3cb179';
export const WDS_MODALS_GREEN_GREEN7 = '#1b543a';
export const WDS_MODALS_GREEN_GREEN12 = '#e5fbeb';
export const WDS_MODALS_GREEN_GREEN6 = '#164430';
export const WDS_MODALS_GREEN_GREEN5 = '#133929';
export const WDS_MODALS_GREEN_GREEN11 = '#4cc38a';
export const WDS_MODALS_GREEN_GREEN4 = '#113123';
export const WDS_MODALS_GREEN_GREEN3 = '#0f291e';
export const WDS_MODALS_GREEN_GREEN8 = '#236e4a';
export const WDS_MODALS_GREEN_GREEN2 = '#0c1f17';
export const WDS_MODALS_GREEN_GREEN1 = '#0d1912';
export const WDS_MODALS_GRASS_GRASS10 = '#55b467';
export const WDS_MODALS_GRASS_GRASS6 = '#1d4427';
export const WDS_MODALS_GRASS_GRASS9 = '#46a758';
export const WDS_MODALS_GRASS_GRASS8 = '#2f6e3b';
export const WDS_MODALS_GRASS_GRASS12 = '#e5fbeb';
export const WDS_MODALS_GRASS_GRASS5 = '#193921';
export const WDS_MODALS_GRASS_GRASS7 = '#245530';
export const WDS_MODALS_GRASS_GRASS4 = '#16301d';
export const WDS_MODALS_GRASS_GRASS3 = '#132819';
export const WDS_MODALS_GRASS_GRASS2 = '#0f1e13';
export const WDS_MODALS_GRASS_GRASS1 = '#0d1912';
export const WDS_MODALS_GRASS_GRASS11 = '#63c174';
export const WDS_MODALS_ORANGE_ORANGE10 = '#ff802b';
export const WDS_MODALS_ORANGE_ORANGE9 = '#f76808';
export const WDS_MODALS_ORANGE_ORANGE11 = '#ff8b3e';
export const WDS_MODALS_ORANGE_ORANGE8 = '#943e00';
export const WDS_MODALS_ORANGE_ORANGE2 = '#2b1400';
export const WDS_MODALS_ORANGE_ORANGE7 = '#763205';
export const WDS_MODALS_ORANGE_ORANGE4 = '#441f04';
export const WDS_MODALS_ORANGE_ORANGE12 = '#feeadd';
export const WDS_MODALS_ORANGE_ORANGE5 = '#4f2305';
export const WDS_MODALS_ORANGE_ORANGE3 = '#391a03';
export const WDS_MODALS_ORANGE_ORANGE6 = '#5f2a06';
export const WDS_MODALS_ORANGE_ORANGE1 = '#1f1206';
export const WDS_MODALS_BROWN_BROWN10 = '#bd8b60';
export const WDS_MODALS_BROWN_BROWN9 = '#ad7f58';
export const WDS_MODALS_BROWN_BROWN7 = '#5c4332';
export const WDS_MODALS_BROWN_BROWN6 = '#493528';
export const WDS_MODALS_BROWN_BROWN5 = '#3e2c22';
export const WDS_MODALS_BROWN_BROWN1 = '#191513';
export const WDS_MODALS_BROWN_BROWN12 = '#faf0e5';
export const WDS_MODALS_BROWN_BROWN2 = '#221813';
export const WDS_MODALS_BROWN_BROWN3 = '#2e201a';
export const WDS_MODALS_BROWN_BROWN8 = '#775940';
export const WDS_MODALS_BROWN_BROWN4 = '#36261e';
export const WDS_MODALS_BROWN_BROWN11 = '#dba16e';
export const WDS_MODALS_SKY_SKY10 = '#8ae8ff';
export const WDS_MODALS_SKY_SKY8 = '#005d85';
export const WDS_MODALS_SKY_SKY12 = '#eaf8ff';
export const WDS_MODALS_SKY_SKY7 = '#064b6b';
export const WDS_MODALS_SKY_SKY6 = '#083e59';
export const WDS_MODALS_SKY_SKY11 = '#2ec8ee';
export const WDS_MODALS_SKY_SKY5 = '#08354c';
export const WDS_MODALS_SKY_SKY3 = '#082636';
export const WDS_MODALS_SKY_SKY9 = '#68ddfd';
export const WDS_MODALS_SKY_SKY1 = '#0c1820';
export const WDS_MODALS_SKY_SKY2 = '#071d2a';
export const WDS_MODALS_SKY_SKY4 = '#082d41';
export const WDS_MODALS_MINT_MINT10 = '#95f3d9';
export const WDS_MODALS_MINT_MINT12 = '#e7fcf7';
export const WDS_MODALS_MINT_MINT3 = '#052926';
export const WDS_MODALS_MINT_MINT8 = '#006d5b';
export const WDS_MODALS_MINT_MINT7 = '#00564a';
export const WDS_MODALS_MINT_MINT6 = '#01453d';
export const WDS_MODALS_MINT_MINT4 = '#04312c';
export const WDS_MODALS_MINT_MINT11 = '#25d0ab';
export const WDS_MODALS_MINT_MINT9 = '#70e1c8';
export const WDS_MODALS_MINT_MINT5 = '#033a34';
export const WDS_MODALS_MINT_MINT2 = '#05201e';
export const WDS_MODALS_MINT_MINT1 = '#081917';
export const WDS_MODALS_LIME_LIME9 = '#99d52a';
export const WDS_MODALS_LIME_LIME4 = '#252e0f';
export const WDS_MODALS_LIME_LIME8 = '#536716';
export const WDS_MODALS_LIME_LIME10 = '#c4f042';
export const WDS_MODALS_LIME_LIME11 = '#87be22';
export const WDS_MODALS_LIME_LIME7 = '#415215';
export const WDS_MODALS_LIME_LIME6 = '#344213';
export const WDS_MODALS_LIME_LIME5 = '#2b3711';
export const WDS_MODALS_LIME_LIME12 = '#effbdd';
export const WDS_MODALS_LIME_LIME2 = '#181d08';
export const WDS_MODALS_LIME_LIME3 = '#1e260d';
export const WDS_MODALS_LIME_LIME1 = '#141807';
export const WDS_MODALS_YELLOW_YELLOW10 = '#ffef5c';
export const WDS_MODALS_YELLOW_YELLOW4 = '#352800';
export const WDS_MODALS_YELLOW_YELLOW9 = '#f5d90a';
export const WDS_MODALS_YELLOW_YELLOW2 = '#221a00';
export const WDS_MODALS_YELLOW_YELLOW8 = '#705e00';
export const WDS_MODALS_YELLOW_YELLOW7 = '#594a05';
export const WDS_MODALS_YELLOW_YELLOW5 = '#3e3000';
export const WDS_MODALS_YELLOW_YELLOW1 = '#1c1500';
export const WDS_MODALS_YELLOW_YELLOW3 = '#2c2100';
export const WDS_MODALS_YELLOW_YELLOW12 = '#fffad1';
export const WDS_MODALS_YELLOW_YELLOW6 = '#493c00';
export const WDS_MODALS_YELLOW_YELLOW11 = '#f0c000';
export const WDS_MODALS_AMBER_AMBER10 = '#ffcb47';
export const WDS_MODALS_AMBER_AMBER9 = '#ffb224';
export const WDS_MODALS_AMBER_AMBER6 = '#573300';
export const WDS_MODALS_AMBER_AMBER11 = '#f1a10d';
export const WDS_MODALS_AMBER_AMBER7 = '#693f05';
export const WDS_MODALS_AMBER_AMBER4 = '#3f2200';
export const WDS_MODALS_AMBER_AMBER5 = '#4a2900';
export const WDS_MODALS_AMBER_AMBER1 = '#1f1300';
export const WDS_MODALS_AMBER_AMBER12 = '#fef3dd';
export const WDS_MODALS_AMBER_AMBER8 = '#824e00';
export const WDS_MODALS_AMBER_AMBER2 = '#271700';
export const WDS_MODALS_AMBER_AMBER3 = '#341c00';
export const WDS_MODALS_GRAY_GRAY10 = '#7e7e7e';
export const WDS_MODALS_GRAY_GRAY9 = '#707070';
export const WDS_MODALS_GRAY_GRAY8 = '#505050';
export const WDS_MODALS_GRAY_GRAY7 = '#3e3e3e';
export const WDS_MODALS_GRAY_GRAY5 = '#2e2e2e';
export const WDS_MODALS_GRAY_GRAY3 = '#232323';
export const WDS_MODALS_GRAY_GRAY1 = '#161616';
export const WDS_MODALS_GRAY_GRAY12 = '#ededed';
export const WDS_MODALS_GRAY_GRAY11 = '#a0a0a0';
export const WDS_MODALS_GRAY_GRAY6 = '#343434';
export const WDS_MODALS_GRAY_GRAY4 = '#282828';
export const WDS_MODALS_GRAY_GRAY2 = '#1c1c1c';
export const WDS_MODALS_MAUVE_MAUVE10 = '#7e7d86';
export const WDS_MODALS_MAUVE_MAUVE7 = '#3e3e44';
export const WDS_MODALS_MAUVE_MAUVE5 = '#2e2e32';
export const WDS_MODALS_MAUVE_MAUVE8 = '#504f57';
export const WDS_MODALS_MAUVE_MAUVE6 = '#34343a';
export const WDS_MODALS_MAUVE_MAUVE4 = '#28282c';
export const WDS_MODALS_MAUVE_MAUVE1 = '#161618';
export const WDS_MODALS_MAUVE_MAUVE12 = '#ededef';
export const WDS_MODALS_MAUVE_MAUVE11 = '#a09fa6';
export const WDS_MODALS_MAUVE_MAUVE2 = '#1c1c1f';
export const WDS_MODALS_MAUVE_MAUVE9 = '#706f78';
export const WDS_MODALS_MAUVE_MAUVE3 = '#232326';
export const WDS_MODALS_SLATE_SLATE6 = '#313538';
export const WDS_MODALS_SLATE_SLATE9 = '#697177';
export const WDS_MODALS_SLATE_SLATE4 = '#26292b';
export const WDS_MODALS_SLATE_SLATE7 = '#3a3f42';
export const WDS_MODALS_SLATE_SLATE8 = '#4c5155';
export const WDS_MODALS_SLATE_SLATE5 = '#2b2f31';
export const WDS_MODALS_SLATE_SLATE10 = '#787f85';
export const WDS_MODALS_SLATE_SLATE1 = '#151718';
export const WDS_MODALS_SLATE_SLATE11 = '#9ba1a6';
export const WDS_MODALS_SLATE_SLATE2 = '#1a1d1e';
export const WDS_MODALS_SLATE_SLATE3 = '#202425';
export const WDS_MODALS_SLATE_SLATE12 = '#ecedee';
export const WDS_MODALS_SAGE_SAGE7 = '#393f3c';
export const WDS_MODALS_SAGE_SAGE6 = '#303633';
export const WDS_MODALS_SAGE_SAGE3 = '#1f2421';
export const WDS_MODALS_SAGE_SAGE11 = '#99a29e';
export const WDS_MODALS_SAGE_SAGE9 = '#66736d';
export const WDS_MODALS_SAGE_SAGE5 = '#2a2f2c';
export const WDS_MODALS_SAGE_SAGE10 = '#75817b';
export const WDS_MODALS_SAGE_SAGE4 = '#252a27';
export const WDS_MODALS_SAGE_SAGE1 = '#141716';
export const WDS_MODALS_SAGE_SAGE12 = '#eceeed';
export const WDS_MODALS_SAGE_SAGE8 = '#4a524e';
export const WDS_MODALS_SAGE_SAGE2 = '#191d1b';
export const WDS_MODALS_OLIVE_OLIVE10 = '#778175';
export const WDS_MODALS_OLIVE_OLIVE8 = '#4c514b';
export const WDS_MODALS_OLIVE_OLIVE6 = '#313530';
export const WDS_MODALS_OLIVE_OLIVE1 = '#151715';
export const WDS_MODALS_OLIVE_OLIVE9 = '#687366';
export const WDS_MODALS_OLIVE_OLIVE5 = '#2b2f2a';
export const WDS_MODALS_OLIVE_OLIVE4 = '#262925';
export const WDS_MODALS_OLIVE_OLIVE3 = '#20241f';
export const WDS_MODALS_OLIVE_OLIVE12 = '#eceeec';
export const WDS_MODALS_OLIVE_OLIVE11 = '#9aa299';
export const WDS_MODALS_OLIVE_OLIVE7 = '#3b3f3a';
export const WDS_MODALS_OLIVE_OLIVE2 = '#1a1d19';
export const WDS_MODALS_SAND_SAND10 = '#7f7e77';
export const WDS_MODALS_SAND_SAND6 = '#353431';
export const WDS_MODALS_SAND_SAND4 = '#282826';
export const WDS_MODALS_SAND_SAND9 = '#717069';
export const WDS_MODALS_SAND_SAND7 = '#3e3e3a';
export const WDS_MODALS_SAND_SAND5 = '#2e2e2b';
export const WDS_MODALS_SAND_SAND12 = '#ededec';
export const WDS_MODALS_SAND_SAND2 = '#1c1c1a';
export const WDS_MODALS_SAND_SAND11 = '#a1a09a';
export const WDS_MODALS_SAND_SAND3 = '#232320';
export const WDS_MODALS_SAND_SAND8 = '#51504b';
export const WDS_MODALS_SAND_SAND1 = '#161615';
export const WDS_MODALS_GOLD_GOLD7 = '#504737';
export const WDS_MODALS_GOLD_GOLD8 = '#6b5d48';
export const WDS_MODALS_GOLD_GOLD6 = '#3e382c';
export const WDS_MODALS_GOLD_GOLD5 = '#353026';
export const WDS_MODALS_GOLD_GOLD4 = '#2e2a21';
export const WDS_MODALS_GOLD_GOLD10 = '#a59071';
export const WDS_MODALS_GOLD_GOLD1 = '#171613';
export const WDS_MODALS_GOLD_GOLD9 = '#978365';
export const WDS_MODALS_GOLD_GOLD3 = '#26231c';
export const WDS_MODALS_GOLD_GOLD12 = '#ffffff';
export const WDS_MODALS_GOLD_GOLD11 = '#bfa888';
export const WDS_MODALS_GOLD_GOLD2 = '#1c1a15';
export const WDS_MODALS_BRONZE_BRONZE10 = '#b08c7d';
export const WDS_MODALS_BRONZE_BRONZE1 = '#191514';
export const WDS_MODALS_BRONZE_BRONZE9 = '#a18072';
export const WDS_MODALS_BRONZE_BRONZE8 = '#74594e';
export const WDS_MODALS_BRONZE_BRONZE11 = '#cba393';
export const WDS_MODALS_BRONZE_BRONZE5 = '#3b2e29';
export const WDS_MODALS_BRONZE_BRONZE4 = '#332824';
export const WDS_MODALS_BRONZE_BRONZE2 = '#1f1917';
export const WDS_MODALS_BRONZE_BRONZE3 = '#2a211f';
export const WDS_MODALS_BRONZE_BRONZE12 = '#f9ede7';
export const WDS_MODALS_BRONZE_BRONZE7 = '#57433c';
export const WDS_MODALS_BRONZE_BRONZE6 = '#453530';
export const WDS_MODALS_CRIMSON_CRIMSON10 = '#f04f88';
export const WDS_MODALS_CRIMSON_CRIMSON6 = '#641d3b';
export const WDS_MODALS_CRIMSON_CRIMSON9 = '#e93d82';
export const WDS_MODALS_CRIMSON_CRIMSON4 = '#481a2d';
export const WDS_MODALS_CRIMSON_CRIMSON7 = '#801d45';
export const WDS_MODALS_CRIMSON_CRIMSON5 = '#541b33';
export const WDS_MODALS_CRIMSON_CRIMSON11 = '#f76190';
export const WDS_MODALS_CRIMSON_CRIMSON12 = '#feecf4';
export const WDS_MODALS_CRIMSON_CRIMSON2 = '#27141c';
export const WDS_MODALS_CRIMSON_CRIMSON3 = '#3c1827';
export const WDS_MODALS_CRIMSON_CRIMSON8 = '#ae1955';
export const WDS_MODALS_CRIMSON_CRIMSON1 = '#1d1418';
export const WDS_MODALS_PINK_PINK10 = '#e34ba9';
export const WDS_MODALS_PINK_PINK9 = '#d6409f';
export const WDS_MODALS_PINK_PINK7 = '#7a1d5a';
export const WDS_MODALS_PINK_PINK1 = '#1f121b';
export const WDS_MODALS_PINK_PINK11 = '#f65cb6';
export const WDS_MODALS_PINK_PINK6 = '#601d48';
export const WDS_MODALS_PINK_PINK8 = '#a71873';
export const WDS_MODALS_PINK_PINK5 = '#501b3f';
export const WDS_MODALS_PINK_PINK4 = '#451a37';
export const WDS_MODALS_PINK_PINK3 = '#3a182f';
export const WDS_MODALS_PINK_PINK12 = '#feebf7';
export const WDS_MODALS_PINK_PINK2 = '#271421';
export const WDS_MODALS_PLUM_PLUM10 = '#bd54c6';
export const WDS_MODALS_PLUM_PLUM9 = '#ab4aba';
export const WDS_MODALS_PLUM_PLUM12 = '#fbecfc';
export const WDS_MODALS_PLUM_PLUM8 = '#883894';
export const WDS_MODALS_PLUM_PLUM6 = '#542658';
export const WDS_MODALS_PLUM_PLUM2 = '#251425';
export const WDS_MODALS_PLUM_PLUM5 = '#48214b';
export const WDS_MODALS_PLUM_PLUM11 = '#d864d8';
export const WDS_MODALS_PLUM_PLUM4 = '#3e1d40';
export const WDS_MODALS_PLUM_PLUM7 = '#692d6f';
export const WDS_MODALS_PLUM_PLUM3 = '#341a34';
export const WDS_MODALS_PLUM_PLUM1 = '#1d131d';
export const WDS_MODALS_PURPLE_PURPLE10 = '#9d5bd2';
export const WDS_MODALS_PURPLE_PURPLE3 = '#301a3a';
export const WDS_MODALS_PURPLE_PURPLE8 = '#7938b2';
export const WDS_MODALS_PURPLE_PURPLE7 = '#5f2d84';
export const WDS_MODALS_PURPLE_PURPLE4 = '#3a1e48';
export const WDS_MODALS_PURPLE_PURPLE1 = '#1b141d';
export const WDS_MODALS_PURPLE_PURPLE6 = '#4e2667';
export const WDS_MODALS_PURPLE_PURPLE2 = '#221527';
export const WDS_MODALS_PURPLE_PURPLE12 = '#f7ecfc';
export const WDS_MODALS_PURPLE_PURPLE11 = '#bf7af0';
export const WDS_MODALS_PURPLE_PURPLE9 = '#8e4ec6';
export const WDS_MODALS_PURPLE_PURPLE5 = '#432155';
export const WDS_MODALS_OVERLAY_WHITE_WHITE10 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE8 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE7 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE5 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE4 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE2 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE3 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE12 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE9 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE11 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE6 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE1 = '#ffffff';
export const WDS_MODALS_OVERLAY_BLACK_BLACK9 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK8 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK6 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK5 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK4 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK3 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK7 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK12 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK11 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK10 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK2 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK1 = '#000000';
export const WDS_THEME_ACCENT_COLOR1 = '#0085a3'; // Background
export const WDS_THEME_ACCENT_COLOR2 = '#0092b2'; // Subtle Background
export const WDS_THEME_ACCENT_COLOR3 = '#009ec2'; // UI Background
export const WDS_THEME_ACCENT_COLOR4 = '#00abd1'; // Hover Background
export const WDS_THEME_ACCENT_COLOR5 = '#00b7e0'; // Active UI Background
export const WDS_THEME_ACCENT_COLOR6 = '#00c8f5'; // Subtle Border
export const WDS_THEME_ACCENT_COLOR7 = '#05d1ff'; // Strong Border
export const WDS_THEME_ACCENT_COLOR8 = '#14d4ff'; // Hover Border
export const WDS_THEME_ACCENT_COLOR9 = '#24d7ff'; // Primary
export const WDS_THEME_ACCENT_COLOR10 = '#33daff'; // Hover Primary
export const WDS_THEME_ACCENT_COLOR11 = '#ddd9f2'; // Subtle Text
export const WDS_THEME_ACCENT_COLOR12 = '#eeecf9'; // Text
export const WDS_THEME_BASE_COLOR10 = '#808080'; // Hover Primary
export const WDS_THEME_BASE_COLOR6 = '#4d5151'; // Subtle Border
export const WDS_THEME_BASE_COLOR5 = '#434545'; // Active UI Background
export const WDS_THEME_BASE_COLOR8 = '#6a6f6e'; // Hover Border
export const WDS_THEME_BASE_COLOR12 = '#fdfcfc'; // Text
export const WDS_THEME_BASE_COLOR3 = '#1e2222'; // UI Background
export const WDS_THEME_BASE_COLOR9 = '#767878'; // Primary
export const WDS_THEME_BASE_COLOR7 = '#5f6262'; // Strong Border
export const WDS_THEME_BASE_COLOR4 = '#303131'; // Hover Background
export const WDS_THEME_BASE_COLOR11 = '#e6f4f2'; // Subtle Text
export const WDS_THEME_BASE_COLOR2 = '#0d1111'; // Subtle Background
export const WDS_THEME_BASE_COLOR1 = '#030202'; // Background
export const WDS_THEME_GHOST_COLOR1 = '#030202'; // Background
export const WDS_THEME_GHOST_COLOR2 = '#0d1111'; // Subtle Background
export const WDS_THEME_GHOST_COLOR3 = '#1e2222'; // UI Background
export const WDS_THEME_GHOST_COLOR4 = '#303131'; // Hover Background
export const WDS_THEME_GHOST_COLOR5 = '#434545'; // Active UI Background
export const WDS_THEME_GHOST_COLOR6 = '#4d5151'; // Subtle Border
export const WDS_THEME_GHOST_COLOR7 = '#5f6262'; // Strong Border
export const WDS_THEME_GHOST_COLOR8 = '#6a6f6e'; // Hover Border
export const WDS_THEME_GHOST_COLOR9 = '#767878'; // Primary
export const WDS_THEME_GHOST_COLOR10 = '#808080'; // Hover Primary
export const WDS_THEME_GHOST_COLOR11 = '#e6f4f2'; // Subtle Text
export const WDS_THEME_GHOST_COLOR12 = '#fdfcfc'; // Text
export const WDS_THEME_ALIAS_SURFACE_DEFAULT = '#030202'; // Background
export const WDS_THEME_ALIAS_SURFACE_SUBTLE = '#0d1111'; // Subtle Background
export const WDS_THEME_ALIAS_SURFACE_UI = '#1e2222'; // UI Background
export const WDS_THEME_ALIAS_COLOR4 = '#303131'; // Hover Background
export const WDS_THEME_ALIAS_COLOR5 = '#434545'; // Active UI Background
export const WDS_THEME_ALIAS_COLOR6 = '#4d5151'; // Subtle Border
export const WDS_THEME_ALIAS_COLOR7 = '#5f6262'; // Strong Border
export const WDS_THEME_ALIAS_COLOR8 = '#6a6f6e'; // Hover Border
export const WDS_THEME_ALIAS_COLOR9 = '#767878'; // Primary
export const WDS_THEME_ALIAS_COLOR10 = '#808080'; // Hover Primary
export const WDS_THEME_ALIAS_COLOR11 = '#e6f4f2'; // Subtle Text
export const WDS_THEME_ALIAS_COLOR12 = '#fdfcfc'; // Text
