import { createFont } from 'tamagui';

export const fonts = {
  'wds.display.large.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '48px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.large.reguler': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '48px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.large.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '48px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.large.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '48px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.large.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '48px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.large.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '48px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.large.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '48px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.small.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '44px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.small.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '44px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.small.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '44px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.small.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '44px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.small.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '44px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.small.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '44px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.small.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '44px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h1.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '44px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h1.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '44px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h1.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '44px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h1.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '44px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h1.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '44px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h1.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '44px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h2.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '32px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h2.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '32px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h2.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '32px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h2.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '32px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h2.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '32px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h2.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '32px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h3.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '28px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h3.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '28px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h3.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '28px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h3.semilbold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '28px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h3.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '28px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h3.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '28px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h4.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '24px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h4.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '24px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h4.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '24px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h4.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '24px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h4.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '24px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h4.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '24px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h5.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h5.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h5.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h5.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h5.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h5.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h6.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '18px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h6.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '18px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h6.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '18px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h6.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '18px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h6.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '18px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h6.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '18px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.page.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '48px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.page.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '48px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.page.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '48px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.page.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '48px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.page.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '48px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.page.extra.bold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '48px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.page.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '48px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.hero.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '48px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.hero.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '48px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.hero.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '48px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.hero.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '48px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.hero.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '48px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.hero.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '48px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.hero.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '48px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.subtitle.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.subtitle.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.subtitle.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.subtitle.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.subtitle.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.subtitle.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.subtitle.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.small.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.small.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.small.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.small.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.small.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.small.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.small.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.large.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '16px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.large.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.large.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.large.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '16px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.large.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '16px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.large.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '16px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.large.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '16px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.large.italic': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.code.light': {
    fontFamily: 'Roboto Mono',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '100%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.code.regular': {
    fontFamily: 'Roboto Mono',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '100%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.code.bold': {
    fontFamily: 'Roboto Mono',
    fontWeight: 700,
    fontSize: '16px',
    lineHeight: '100%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.link.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '16px',
    lineHeight: '125%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.link.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '125%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.link.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '16px',
    lineHeight: '125%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.2xs': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '10px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.xs': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '12px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.sm': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.md': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.lg': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '18px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.xl': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '20px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.2xl': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '24px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.3xl': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '32px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.4xl': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '36px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.5xl': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '48px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.6xl': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '48px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.7xl': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '48px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.8xl': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '72px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.2xs': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '10px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.xs': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '12px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.sm': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '14px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.md': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '16px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.lg': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '18px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.xl': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '20px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.2xl': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '24px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.3xl': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '32px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.4xl': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '36px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.5xl': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '48px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.6xl': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '48px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.7xl': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '48px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.8xl': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '72px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.small.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '12px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.small.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '12px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.small.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '12px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.small.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '12px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.small.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '12px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.small.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '12px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.small.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '12px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.medium.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '14px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.medium.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.medium.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '14px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.medium.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '14px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.medium.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '14px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.medium.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '14px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.medium.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '14px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.large.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '16px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.large.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.large.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.large.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '16px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.large.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '16px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.large.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '16px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.large.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '16px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.utilities.component.notes.regular': {
    fontFamily: 'Roboto Mono',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.utilities.component.notes.bold': {
    fontFamily: 'Roboto Mono',
    fontWeight: '700',
    fontSize: '16px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
};

export const display_font = createFont({
  family: 'Inter',
  weight: {
    light: 300,
    reguler: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    strong: 900,
    regular: 400,
  },
  size: { large: 48, small: 44 },
  lineHeight: { large: 50.4, small: 46.2 },
});

export const heading_font = createFont({
  family: 'Inter',
  weight: {
    light: 300,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    strong: 900,
    regular: 400,
    semilbold: 700,
  },
  size: { h1: 44, h2: 32, h3: 28, h4: 24, h5: 20, h6: 18, subtitle: 14 },
  lineHeight: { h1: 50.6, h2: 36.8, h3: 32.2, h4: 27.6, h5: 23, h6: 20.7, subtitle: 19.6 },
});

export const heading_title_font = createFont({
  family: 'Inter',
  weight: {
    light: 300,
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extra: 800,
    strong: 900,
    extrabold: 800,
  },
  size: { title: 48 },
  lineHeight: { title: 57.6 },
});

export const paragraph_body_font = createFont({
  family: 'Inter',
  weight: {
    regular: 400,
    light: 300,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    strong: 900,
    italic: 400,
  },
  size: { body: 16 },
  lineHeight: { body: 22.4 },
});

export const paragraph_font = createFont({
  family: 'Inter',
  weight: { light: 300, regular: 400, bold: 700 },
  size: { code: 16, link: 16 },
  lineHeight: { code: 16, link: 20 },
});

export const text_font = createFont({
  family: 'Inter',
  weight: { regular: 400, bold: 700 },
  size: {
    '2xs': 10,
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 20,
    '2xl': 24,
    '3xl': 32,
    '4xl': 36,
    '5xl': 48,
    '6xl': 48,
    '7xl': 48,
    '8xl': 72,
  },
  lineHeight: {
    '2xs': 12,
    xs: 14.4,
    sm: 16.8,
    md: 19.2,
    lg: 21.6,
    xl: 24,
    '2xl': 28.8,
    '3xl': 38.4,
    '4xl': 43.2,
    '5xl': 57.6,
    '6xl': 57.6,
    '7xl': 57.6,
    '8xl': 86.4,
  },
});

export const label_font = createFont({
  family: 'Inter',
  weight: {
    light: 300,
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    strong: 900,
  },
  size: { small: 12, medium: 14, large: 16 },
  lineHeight: { small: 13.8, medium: 16.1, large: 18.4 },
});

export const utilities_component_font = createFont({
  family: 'Roboto Mono',
  weight: { regular: '400', bold: '700' },
  size: { component: 16 },
  lineHeight: { component: 22.4 },
});

export const aggregation = {
  display: display_font,
  heading: heading_font,
  'heading.title': heading_title_font,
  'paragraph.body': paragraph_body_font,
  paragraph: paragraph_font,
  text: text_font,
  label: label_font,
  'utilities.component': utilities_component_font,
};
