/**
 * Do not edit directly, this file was auto-generated.
 */

export const WDS_SIZE_SPACE_0 = '0px';
export const WDS_SIZE_SPACE_100 = '4px';
export const WDS_SIZE_SPACE_150 = '6px';
export const WDS_SIZE_SPACE_200 = '8px';
export const WDS_SIZE_SPACE_300 = '12px';
export const WDS_SIZE_SPACE_400 = '16px';
export const WDS_SIZE_SPACE_600 = '24px';
export const WDS_SIZE_SPACE_800 = '32px';
export const WDS_SIZE_SPACE_1200 = '48px';
export const WDS_SIZE_SPACE_1600 = '64px';
export const WDS_SIZE_SPACE_2400 = '96px';
export const WDS_SIZE_SPACE_3000 = '128px';
export const WDS_SIZE_SPACE_4000 = '160px';
export const WDS_SIZE_SPACE_NEGATIVE_100 = '-4px';
export const WDS_SIZE_SPACE_NEGATIVE_200 = '-8px';
export const WDS_SIZE_SPACE_NEGATIVE_300 = '-12px';
export const WDS_SIZE_SPACE_NEGATIVE_400 = '-16px';
export const WDS_SIZE_SPACE_NEGATIVE_600 = '-24px';
export const WDS_SIZE_SPACE_050 = '2px';
export const WDS_SIZE_RADIUS_100 = '4px';
export const WDS_SIZE_RADIUS_200 = '10px';
export const WDS_SIZE_RADIUS_300 = '16px';
export const WDS_SIZE_RADIUS_400 = '20px';
export const WDS_SIZE_RADIUS_480 = '48px';
export const WDS_SIZE_RADIUS_500 = '50px';
export const WDS_SIZE_RADIUS_600 = '60px';
export const WDS_SIZE_RADIUS_FULL = '9999px';
export const WDS_SIZE_DEPTH_0 = '0px';
export const WDS_SIZE_DEPTH_100 = '4px';
export const WDS_SIZE_DEPTH_200 = '8px';
export const WDS_SIZE_DEPTH_400 = '16px';
export const WDS_SIZE_DEPTH_800 = '32px';
export const WDS_SIZE_DEPTH_1200 = '48px';
export const WDS_SIZE_DEPTH_025 = '1px';
export const WDS_SIZE_DEPTH_NEGATIVE_025 = '-1px';
export const WDS_SIZE_DEPTH_NEGATIVE_100 = '-4px';
export const WDS_SIZE_DEPTH_NEGATIVE_200 = '-8px';
export const WDS_SIZE_DEPTH_NEGATIVE_400 = '-16px';
export const WDS_SIZE_DEPTH_NEGATIVE_800 = '-32px';
export const WDS_SIZE_DEPTH_NEGATIVE_1200 = '-48px';
export const WDS_SIZE_BORDER_100 = '1px';
export const WDS_SIZE_BORDER_200 = '2px';
export const WDS_SIZE_BORDER_250 = '2.5px';
export const WDS_SIZE_BORDER_300 = '3px';
export const WDS_SIZE_BORDER_400 = '4px';
export const WDS_SIZE_BORDER_500 = '5px';
export const WDS_SIZE_RING_100 = '2px';
export const WDS_SIZE_RING_200 = '2px';
export const WDS_SIZE_RING_300 = '2px';
export const WDS_SIZE_RING_400 = '2px';
export const WDS_SIZE_RING_500 = '2px';
export const WDS_SIZE_BLUR_100 = '4px';
export const WDS_SIZE_ICON_SMALL = '24px';
export const WDS_SIZE_ICON_MEDIUM = '32px';
export const WDS_SIZE_ICON_LARGE = '40px';
export const WDS_SIZE_ICON_2_X_LARGE = '80px';
export const WDS_SIZE_ICON_X_LARGE = '60px';
export const WDS_SIZE_ICON_3_X_LARGE = '100px';
export const WDS_SIZE_PADDING_DESKTOP = '24px';
export const WDS_TYPOGRAPHY_FONT_SIZE_2XL = '24px'; // fontSize variable for 24
export const WDS_TYPOGRAPHY_FONT_SIZE_XS = '10px'; // fontSize variable for 10
export const WDS_TYPOGRAPHY_FONT_SIZE_BASE = '14px'; // fontSize variable for 14
export const WDS_TYPOGRAPHY_FONT_SIZE_8XL = '48px'; // fontSize variable for 52
export const WDS_TYPOGRAPHY_FONT_SIZE_10XL = '48px'; // fontSize variable for 52
export const WDS_TYPOGRAPHY_FONT_SIZE_5XL = '36px'; // fontSize variable for 36
export const WDS_TYPOGRAPHY_FONT_SIZE_11XL = '72px';
export const WDS_TYPOGRAPHY_FONT_SIZE_7XL = '44px'; // fontSize variable for 44
export const WDS_TYPOGRAPHY_FONT_SIZE_SM = '12px'; // fontSize variable for 12
export const WDS_TYPOGRAPHY_FONT_SIZE_9XL = '48px'; // fontSize variable for 52
export const WDS_TYPOGRAPHY_FONT_SIZE_3XL = '28px'; // fontSize variable for 28
export const WDS_TYPOGRAPHY_FONT_SIZE_XL = '20px'; // fontSize variable for 20
export const WDS_TYPOGRAPHY_FONT_SIZE_6XL = '40px'; // fontSize variable for 40
export const WDS_TYPOGRAPHY_FONT_SIZE_MD = '16px'; // fontSize variable for 16
export const WDS_TYPOGRAPHY_FONT_SIZE_LG = '18px'; // fontSize variable for 18
export const WDS_TYPOGRAPHY_FONT_SIZE_4XL = '32px';
