/**
 * Do not edit directly, this file was auto-generated.
 */

export const WDS_SIZE_SPACE_0 = 0;
export const WDS_SIZE_SPACE_100 = 4;
export const WDS_SIZE_SPACE_150 = 6;
export const WDS_SIZE_SPACE_200 = 8;
export const WDS_SIZE_SPACE_300 = 12;
export const WDS_SIZE_SPACE_400 = 16;
export const WDS_SIZE_SPACE_600 = 24;
export const WDS_SIZE_SPACE_800 = 32;
export const WDS_SIZE_SPACE_1200 = 48;
export const WDS_SIZE_SPACE_1600 = 64;
export const WDS_SIZE_SPACE_2400 = 96;
export const WDS_SIZE_SPACE_3000 = 128;
export const WDS_SIZE_SPACE_4000 = 160;
export const WDS_SIZE_SPACE_NEGATIVE_100 = -4;
export const WDS_SIZE_SPACE_NEGATIVE_200 = -8;
export const WDS_SIZE_SPACE_NEGATIVE_300 = -12;
export const WDS_SIZE_SPACE_NEGATIVE_400 = -16;
export const WDS_SIZE_SPACE_NEGATIVE_600 = -24;
export const WDS_SIZE_SPACE_050 = 2;
export const WDS_SIZE_RADIUS_100 = 4;
export const WDS_SIZE_RADIUS_200 = 10;
export const WDS_SIZE_RADIUS_300 = 16;
export const WDS_SIZE_RADIUS_400 = 20;
export const WDS_SIZE_RADIUS_480 = 48;
export const WDS_SIZE_RADIUS_500 = 50;
export const WDS_SIZE_RADIUS_600 = 60;
export const WDS_SIZE_RADIUS_FULL = 9999;
export const WDS_SIZE_DEPTH_0 = 0;
export const WDS_SIZE_DEPTH_100 = 4;
export const WDS_SIZE_DEPTH_200 = 8;
export const WDS_SIZE_DEPTH_400 = 16;
export const WDS_SIZE_DEPTH_800 = 32;
export const WDS_SIZE_DEPTH_1200 = 48;
export const WDS_SIZE_DEPTH_025 = 1;
export const WDS_SIZE_DEPTH_NEGATIVE_025 = -1;
export const WDS_SIZE_DEPTH_NEGATIVE_100 = -4;
export const WDS_SIZE_DEPTH_NEGATIVE_200 = -8;
export const WDS_SIZE_DEPTH_NEGATIVE_400 = -16;
export const WDS_SIZE_DEPTH_NEGATIVE_800 = -32;
export const WDS_SIZE_DEPTH_NEGATIVE_1200 = -48;
export const WDS_SIZE_BORDER_100 = 1;
export const WDS_SIZE_BORDER_200 = 2;
export const WDS_SIZE_BORDER_250 = 2.5;
export const WDS_SIZE_BORDER_300 = 3;
export const WDS_SIZE_BORDER_400 = 4;
export const WDS_SIZE_BORDER_500 = 5;
export const WDS_SIZE_RING_100 = 2;
export const WDS_SIZE_RING_200 = 2;
export const WDS_SIZE_RING_300 = 2;
export const WDS_SIZE_RING_400 = 2;
export const WDS_SIZE_RING_500 = 2;
export const WDS_SIZE_BLUR_100 = 4;
export const WDS_SIZE_ICON_SMALL = 24;
export const WDS_SIZE_ICON_MEDIUM = 32;
export const WDS_SIZE_ICON_LARGE = 40;
export const WDS_SIZE_ICON_2_X_LARGE = 80;
export const WDS_SIZE_ICON_X_LARGE = 60;
export const WDS_SIZE_ICON_3_X_LARGE = 100;
export const WDS_SIZE_ICON_X_SMALL = 18;
export const WDS_SIZE_ICON_2_X_SMALL = 14;
export const WDS_SIZE_PADDING_DESKTOP = 24;
export const WDS_TYPOGRAPHY_FONT_SIZE_2XL = 24; // fontSize variable for 24
export const WDS_TYPOGRAPHY_FONT_SIZE_XS = 10; // fontSize variable for 10
export const WDS_TYPOGRAPHY_FONT_SIZE_BASE = 14; // fontSize variable for 14
export const WDS_TYPOGRAPHY_FONT_SIZE_8XL = 48; // fontSize variable for 52
export const WDS_TYPOGRAPHY_FONT_SIZE_10XL = 48; // fontSize variable for 52
export const WDS_TYPOGRAPHY_FONT_SIZE_5XL = 36; // fontSize variable for 36
export const WDS_TYPOGRAPHY_FONT_SIZE_11XL = 72;
export const WDS_TYPOGRAPHY_FONT_SIZE_7XL = 44; // fontSize variable for 44
export const WDS_TYPOGRAPHY_FONT_SIZE_SM = 12; // fontSize variable for 12
export const WDS_TYPOGRAPHY_FONT_SIZE_9XL = 48; // fontSize variable for 52
export const WDS_TYPOGRAPHY_FONT_SIZE_3XL = 28; // fontSize variable for 28
export const WDS_TYPOGRAPHY_FONT_SIZE_XL = 20; // fontSize variable for 20
export const WDS_TYPOGRAPHY_FONT_SIZE_6XL = 40; // fontSize variable for 40
export const WDS_TYPOGRAPHY_FONT_SIZE_MD = 16; // fontSize variable for 16
export const WDS_TYPOGRAPHY_FONT_SIZE_LG = 18; // fontSize variable for 18
export const WDS_TYPOGRAPHY_FONT_SIZE_4XL = 32;
