import { createFont } from 'tamagui';

export const fonts = {
  'wds.display.large.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '44px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.large.reguler': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '44px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.large.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '44px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.large.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '44px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.large.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '44px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.large.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '44px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.large.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '44px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.small.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '40px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.small.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '40px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.small.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '40px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.small.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '40px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.small.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '40px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.small.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '40px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.display.small.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '40px',
    lineHeight: '105%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h1.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '40px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h1.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '40px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h1.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '40px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h1.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '40px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h1.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '40px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h1.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '40px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h2.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '28px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h2.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '28px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h2.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '28px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h2.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '28px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h2.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '28px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h2.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '28px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h3.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '24px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h3.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '24px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h3.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '24px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h3.semilbold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '24px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h3.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '24px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h3.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '24px',
    lineHeight: '115%',
    letterSpacing: '0px',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h4.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h4.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h4.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h4.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h4.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h4.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h5.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h5.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h5.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h5.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h5.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h5.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '20px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h6.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '16px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h6.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h6.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h6.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '16px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h6.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '16px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.h6.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '16px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.page.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '44px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.page.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '44px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.page.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '44px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.page.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '44px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.page.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '44px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.page.extra.bold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '44px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.page.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '44px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.hero.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '44px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.hero.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '44px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.hero.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '44px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.hero.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '44px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.hero.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '44px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.hero.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '44px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.title.hero.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '44px',
    lineHeight: '120%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.subtitle.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '12px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.subtitle.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '12px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.subtitle.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '12px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.subtitle.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '12px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.subtitle.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '12px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.subtitle.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '12px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.heading.subtitle.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '12px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.small.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '12px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.small.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '12px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.small.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '12px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.small.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '12px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.small.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '12px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.small.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '12px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.small.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '12px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.large.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.large.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.large.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.large.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.large.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.large.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.large.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.body.large.italic': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.code.light': {
    fontFamily: 'Roboto Mono',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '100%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.code.regular': {
    fontFamily: 'Roboto Mono',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '100%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.code.bold': {
    fontFamily: 'Roboto Mono',
    fontWeight: 700,
    fontSize: '14px',
    lineHeight: '100%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.link.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '14px',
    lineHeight: '125%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.link.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '125%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.paragraph.link.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '14px',
    lineHeight: '125%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.2xs': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '8px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.xs': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '10px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.sm': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '12px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.md': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.lg': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.xl': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '20px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.2xl': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '20px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.3xl': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '28px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.4xl': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '32px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.5xl': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '44px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.6xl': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '44px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.7xl': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '44px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.regular.8xl': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '52px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.2xs': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '8px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.xs': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '10px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.sm': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '12px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.md': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '14px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.lg': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '16px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.xl': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '20px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.2xl': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '20px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.3xl': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '28px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.4xl': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '32px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.5xl': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '44px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.6xl': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '44px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.7xl': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '44px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.text.bold.8xl': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '52px',
    lineHeight: 'auto',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.small.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '10px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.small.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '10px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.small.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '10px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.small.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '10px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.small.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '10px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.small.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '10px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.small.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '10px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.medium.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '12px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.medium.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '12px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.medium.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '12px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.medium.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '12px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.medium.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '12px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.medium.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '12px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.medium.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '12px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.large.light': {
    fontFamily: 'Inter',
    fontWeight: 300,
    fontSize: '14px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.large.regular': {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.large.medium': {
    fontFamily: 'Inter',
    fontWeight: 500,
    fontSize: '14px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.large.semibold': {
    fontFamily: 'Inter',
    fontWeight: 600,
    fontSize: '14px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.large.bold': {
    fontFamily: 'Inter',
    fontWeight: 700,
    fontSize: '14px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.large.extrabold': {
    fontFamily: 'Inter',
    fontWeight: 800,
    fontSize: '14px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.label.large.strong': {
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: '14px',
    lineHeight: '115%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.utilities.component.notes.regular': {
    fontFamily: 'Roboto Mono',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
  'wds.utilities.component.notes.bold': {
    fontFamily: 'Roboto Mono',
    fontWeight: '700',
    fontSize: '16px',
    lineHeight: '140%',
    letterSpacing: '0%',
    paragraphSpacing: '0',
    paragraphIndent: '0',
    textDecoration: 'NONE',
    textCase: 'ORIGINAL',
  },
};

export const variants = {
  'display.large.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 44,
    lineHeight: 46.2,
    letterSpacing: 0,
  } as const,
  'display.large.reguler': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 44,
    lineHeight: 46.2,
    letterSpacing: 0,
  } as const,
  'display.large.medium': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 500,
    fontSize: 44,
    lineHeight: 46.2,
    letterSpacing: 0,
  } as const,
  'display.large.semibold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 44,
    lineHeight: 46.2,
    letterSpacing: 0,
  } as const,
  'display.large.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 44,
    lineHeight: 46.2,
    letterSpacing: 0,
  } as const,
  'display.large.extrabold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 800,
    fontSize: 44,
    lineHeight: 46.2,
    letterSpacing: 0,
  } as const,
  'display.large.strong': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 900,
    fontSize: 44,
    lineHeight: 46.2,
    letterSpacing: 0,
  } as const,
  'display.small.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 40,
    lineHeight: 42,
    letterSpacing: 0,
  } as const,
  'display.small.regular': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 40,
    lineHeight: 42,
    letterSpacing: 0,
  } as const,
  'display.small.medium': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 500,
    fontSize: 40,
    lineHeight: 42,
    letterSpacing: 0,
  } as const,
  'display.small.semibold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 40,
    lineHeight: 42,
    letterSpacing: 0,
  } as const,
  'display.small.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 40,
    lineHeight: 42,
    letterSpacing: 0,
  } as const,
  'display.small.extrabold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 800,
    fontSize: 40,
    lineHeight: 42,
    letterSpacing: 0,
  } as const,
  'display.small.strong': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 900,
    fontSize: 40,
    lineHeight: 42,
    letterSpacing: 0,
  } as const,
  'heading.h1.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 40,
    lineHeight: 46,
    letterSpacing: 0,
  } as const,
  'heading.h1.medium': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 500,
    fontSize: 40,
    lineHeight: 46,
    letterSpacing: 0,
  } as const,
  'heading.h1.semibold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 40,
    lineHeight: 46,
    letterSpacing: 0,
  } as const,
  'heading.h1.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 40,
    lineHeight: 46,
    letterSpacing: 0,
  } as const,
  'heading.h1.extrabold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 800,
    fontSize: 40,
    lineHeight: 46,
    letterSpacing: 0,
  } as const,
  'heading.h1.strong': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 900,
    fontSize: 40,
    lineHeight: 46,
    letterSpacing: 0,
  } as const,
  'heading.h2.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 28,
    lineHeight: 32.2,
    letterSpacing: 0,
  } as const,
  'heading.h2.medium': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 500,
    fontSize: 28,
    lineHeight: 32.2,
    letterSpacing: 0,
  } as const,
  'heading.h2.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 28,
    lineHeight: 32.2,
    letterSpacing: 0,
  } as const,
  'heading.h2.semibold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 28,
    lineHeight: 32.2,
    letterSpacing: 0,
  } as const,
  'heading.h2.extrabold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 800,
    fontSize: 28,
    lineHeight: 32.2,
    letterSpacing: 0,
  } as const,
  'heading.h2.strong': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 900,
    fontSize: 28,
    lineHeight: 32.2,
    letterSpacing: 0,
  } as const,
  'heading.h3.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 24,
    lineHeight: 27.6,
    letterSpacing: 0,
  } as const,
  'heading.h3.regular': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 24,
    lineHeight: 27.6,
    letterSpacing: 0,
  } as const,
  'heading.h3.medium': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 500,
    fontSize: 24,
    lineHeight: 27.6,
    letterSpacing: 0,
  } as const,
  'heading.h3.semilbold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 24,
    lineHeight: 27.6,
    letterSpacing: 0,
  } as const,
  'heading.h3.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 24,
    lineHeight: 27.6,
    letterSpacing: 0,
  } as const,
  'heading.h3.strong': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 900,
    fontSize: 24,
    lineHeight: 27.6,
    letterSpacing: 0,
  } as const,
  'heading.h4.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 20,
    lineHeight: 23,
    letterSpacing: 0,
  } as const,
  'heading.h4.regular': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 20,
    lineHeight: 23,
    letterSpacing: 0,
  } as const,
  'heading.h4.medium': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 500,
    fontSize: 20,
    lineHeight: 23,
    letterSpacing: 0,
  } as const,
  'heading.h4.semibold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 20,
    lineHeight: 23,
    letterSpacing: 0,
  } as const,
  'heading.h4.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 20,
    lineHeight: 23,
    letterSpacing: 0,
  } as const,
  'heading.h4.strong': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 900,
    fontSize: 20,
    lineHeight: 23,
    letterSpacing: 0,
  } as const,
  'heading.h5.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 20,
    lineHeight: 23,
    letterSpacing: 0,
  } as const,
  'heading.h5.regular': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 20,
    lineHeight: 23,
    letterSpacing: 0,
  } as const,
  'heading.h5.medium': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 500,
    fontSize: 20,
    lineHeight: 23,
    letterSpacing: 0,
  } as const,
  'heading.h5.semibold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 20,
    lineHeight: 23,
    letterSpacing: 0,
  } as const,
  'heading.h5.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 20,
    lineHeight: 23,
    letterSpacing: 0,
  } as const,
  'heading.h5.strong': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 900,
    fontSize: 20,
    lineHeight: 23,
    letterSpacing: 0,
  } as const,
  'heading.h6.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 16,
    lineHeight: 18.4,
    letterSpacing: 0,
  } as const,
  'heading.h6.regular': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 18.4,
    letterSpacing: 0,
  } as const,
  'heading.h6.medium': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 500,
    fontSize: 16,
    lineHeight: 18.4,
    letterSpacing: 0,
  } as const,
  'heading.h6.semibold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 16,
    lineHeight: 18.4,
    letterSpacing: 0,
  } as const,
  'heading.h6.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 16,
    lineHeight: 18.4,
    letterSpacing: 0,
  } as const,
  'heading.h6.strong': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 900,
    fontSize: 16,
    lineHeight: 18.4,
    letterSpacing: 0,
  } as const,
  'heading.title.page.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'heading.title.page.regular': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'heading.title.page.medium': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 500,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'heading.title.page.semibold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'heading.title.page.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'heading.title.page.extra.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 800,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'heading.title.page.strong': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 900,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'heading.title.hero.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'heading.title.hero.regular': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'heading.title.hero.medium': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 500,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'heading.title.hero.semibold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'heading.title.hero.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'heading.title.hero.extrabold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 800,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'heading.title.hero.strong': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 900,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'heading.subtitle.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 12,
    lineHeight: 16.8,
    letterSpacing: 0,
  } as const,
  'heading.subtitle.regular': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 12,
    lineHeight: 16.8,
    letterSpacing: 0,
  } as const,
  'heading.subtitle.medium': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 500,
    fontSize: 12,
    lineHeight: 16.8,
    letterSpacing: 0,
  } as const,
  'heading.subtitle.semibold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 12,
    lineHeight: 16.8,
    letterSpacing: 0,
  } as const,
  'heading.subtitle.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 12,
    lineHeight: 16.8,
    letterSpacing: 0,
  } as const,
  'heading.subtitle.extrabold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 800,
    fontSize: 12,
    lineHeight: 16.8,
    letterSpacing: 0,
  } as const,
  'heading.subtitle.strong': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 900,
    fontSize: 12,
    lineHeight: 16.8,
    letterSpacing: 0,
  } as const,
  'paragraph.body.small.regular': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 12,
    lineHeight: 16.8,
    letterSpacing: 0,
  } as const,
  'paragraph.body.small.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 12,
    lineHeight: 16.8,
    letterSpacing: 0,
  } as const,
  'paragraph.body.small.medium': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 500,
    fontSize: 12,
    lineHeight: 16.8,
    letterSpacing: 0,
  } as const,
  'paragraph.body.small.semibold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 12,
    lineHeight: 16.8,
    letterSpacing: 0,
  } as const,
  'paragraph.body.small.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 12,
    lineHeight: 16.8,
    letterSpacing: 0,
  } as const,
  'paragraph.body.small.extrabold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 800,
    fontSize: 12,
    lineHeight: 16.8,
    letterSpacing: 0,
  } as const,
  'paragraph.body.small.strong': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 900,
    fontSize: 12,
    lineHeight: 16.8,
    letterSpacing: 0,
  } as const,
  'paragraph.body.large.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 14,
    lineHeight: 19.6,
    letterSpacing: 0,
  } as const,
  'paragraph.body.large.medium': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 500,
    fontSize: 14,
    lineHeight: 19.6,
    letterSpacing: 0,
  } as const,
  'paragraph.body.large.regular': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: 19.6,
    letterSpacing: 0,
  } as const,
  'paragraph.body.large.semibold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 14,
    lineHeight: 19.6,
    letterSpacing: 0,
  } as const,
  'paragraph.body.large.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 14,
    lineHeight: 19.6,
    letterSpacing: 0,
  } as const,
  'paragraph.body.large.extrabold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 800,
    fontSize: 14,
    lineHeight: 19.6,
    letterSpacing: 0,
  } as const,
  'paragraph.body.large.strong': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 900,
    fontSize: 14,
    lineHeight: 19.6,
    letterSpacing: 0,
  } as const,
  'paragraph.body.large.italic': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: 19.6,
    letterSpacing: 0,
  } as const,
  'paragraph.code.light': {
    fontFamily: 'Roboto Mono',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: 14,
    letterSpacing: 0,
  } as const,
  'paragraph.code.regular': {
    fontFamily: 'Roboto Mono',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: 14,
    letterSpacing: 0,
  } as const,
  'paragraph.code.bold': {
    fontFamily: 'Roboto Mono',
    fontWeight: 700,
    fontSize: 14,
    lineHeight: 14,
    letterSpacing: 0,
  } as const,
  'paragraph.link.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 14,
    lineHeight: 17.5,
    letterSpacing: 0,
  } as const,
  'paragraph.link.regular': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: 17.5,
    letterSpacing: 0,
  } as const,
  'paragraph.link.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 14,
    lineHeight: 17.5,
    letterSpacing: 0,
  } as const,
  'text.regular.2xs': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 8,
    lineHeight: 9.6,
    letterSpacing: 0,
  } as const,
  'text.regular.xs': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0,
  } as const,
  'text.regular.sm': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 12,
    lineHeight: 14.4,
    letterSpacing: 0,
  } as const,
  'text.regular.md': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: 16.8,
    letterSpacing: 0,
  } as const,
  'text.regular.lg': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 19.2,
    letterSpacing: 0,
  } as const,
  'text.regular.xl': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 20,
    lineHeight: 24,
    letterSpacing: 0,
  } as const,
  'text.regular.2xl': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 20,
    lineHeight: 24,
    letterSpacing: 0,
  } as const,
  'text.regular.3xl': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 28,
    lineHeight: 33.6,
    letterSpacing: 0,
  } as const,
  'text.regular.4xl': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 32,
    lineHeight: 38.4,
    letterSpacing: 0,
  } as const,
  'text.regular.5xl': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'text.regular.6xl': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'text.regular.7xl': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'text.regular.8xl': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 52,
    lineHeight: 62.4,
    letterSpacing: 0,
  } as const,
  'text.bold.2xs': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 8,
    lineHeight: 9.6,
    letterSpacing: 0,
  } as const,
  'text.bold.xs': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0,
  } as const,
  'text.bold.sm': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 12,
    lineHeight: 14.4,
    letterSpacing: 0,
  } as const,
  'text.bold.md': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 14,
    lineHeight: 16.8,
    letterSpacing: 0,
  } as const,
  'text.bold.lg': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 16,
    lineHeight: 19.2,
    letterSpacing: 0,
  } as const,
  'text.bold.xl': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 20,
    lineHeight: 24,
    letterSpacing: 0,
  } as const,
  'text.bold.2xl': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 20,
    lineHeight: 24,
    letterSpacing: 0,
  } as const,
  'text.bold.3xl': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 28,
    lineHeight: 33.6,
    letterSpacing: 0,
  } as const,
  'text.bold.4xl': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 32,
    lineHeight: 38.4,
    letterSpacing: 0,
  } as const,
  'text.bold.5xl': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'text.bold.6xl': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'text.bold.7xl': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 44,
    lineHeight: 52.8,
    letterSpacing: 0,
  } as const,
  'text.bold.8xl': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 52,
    lineHeight: 62.4,
    letterSpacing: 0,
  } as const,
  'label.small.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 10,
    lineHeight: 11.5,
    letterSpacing: 0,
  } as const,
  'label.small.regular': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 10,
    lineHeight: 11.5,
    letterSpacing: 0,
  } as const,
  'label.small.medium': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 500,
    fontSize: 10,
    lineHeight: 11.5,
    letterSpacing: 0,
  } as const,
  'label.small.semibold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 10,
    lineHeight: 11.5,
    letterSpacing: 0,
  } as const,
  'label.small.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 10,
    lineHeight: 11.5,
    letterSpacing: 0,
  } as const,
  'label.small.extrabold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 800,
    fontSize: 10,
    lineHeight: 11.5,
    letterSpacing: 0,
  } as const,
  'label.small.strong': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 900,
    fontSize: 10,
    lineHeight: 11.5,
    letterSpacing: 0,
  } as const,
  'label.medium.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 12,
    lineHeight: 13.8,
    letterSpacing: 0,
  } as const,
  'label.medium.regular': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 12,
    lineHeight: 13.8,
    letterSpacing: 0,
  } as const,
  'label.medium.medium': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 500,
    fontSize: 12,
    lineHeight: 13.8,
    letterSpacing: 0,
  } as const,
  'label.medium.semibold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 12,
    lineHeight: 13.8,
    letterSpacing: 0,
  } as const,
  'label.medium.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 12,
    lineHeight: 13.8,
    letterSpacing: 0,
  } as const,
  'label.medium.extrabold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 800,
    fontSize: 12,
    lineHeight: 13.8,
    letterSpacing: 0,
  } as const,
  'label.medium.strong': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 900,
    fontSize: 12,
    lineHeight: 13.8,
    letterSpacing: 0,
  } as const,
  'label.large.light': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 300,
    fontSize: 14,
    lineHeight: 16.1,
    letterSpacing: 0,
  } as const,
  'label.large.regular': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: 16.1,
    letterSpacing: 0,
  } as const,
  'label.large.medium': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 500,
    fontSize: 14,
    lineHeight: 16.1,
    letterSpacing: 0,
  } as const,
  'label.large.semibold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 600,
    fontSize: 14,
    lineHeight: 16.1,
    letterSpacing: 0,
  } as const,
  'label.large.bold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 700,
    fontSize: 14,
    lineHeight: 16.1,
    letterSpacing: 0,
  } as const,
  'label.large.extrabold': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 800,
    fontSize: 14,
    lineHeight: 16.1,
    letterSpacing: 0,
  } as const,
  'label.large.strong': {
    fontFamily: 'Inter' as 'unset',
    fontWeight: 900,
    fontSize: 14,
    lineHeight: 16.1,
    letterSpacing: 0,
  } as const,
  'utilities.component.notes.regular': {
    fontFamily: 'Roboto Mono',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 22.4,
    letterSpacing: 0,
  } as const,
  'utilities.component.notes.bold': {
    fontFamily: 'Roboto Mono',
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 22.4,
    letterSpacing: 0,
  } as const,
} as const;

export const display_font = createFont({
  family: 'Inter',
  weight: {
    light: 300,
    reguler: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    strong: 900,
    regular: 400,
  },
  size: { large: 44, small: 40 },
  lineHeight: { large: 46.2, small: 42 },
  letterSpacing: { large: 0, small: 0 },
});

export const heading_font = createFont({
  family: 'Inter',
  weight: {
    light: 300,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    strong: 900,
    regular: 400,
    semilbold: 700,
  },
  size: { h1: 40, h2: 28, h3: 24, h4: 20, h5: 20, h6: 16, subtitle: 12 },
  lineHeight: { h1: 46, h2: 32.2, h3: 27.6, h4: 23, h5: 23, h6: 18.4, subtitle: 16.8 },
  letterSpacing: { h1: 0, h2: 0, h3: 0, h4: 0, h5: 0, h6: 0, subtitle: 0 },
});

export const heading_title_font = createFont({
  family: 'Inter',
  weight: {
    light: 300,
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extra: 800,
    strong: 900,
    extrabold: 800,
  },
  size: { title: 44 },
  lineHeight: { title: 52.8 },
  letterSpacing: { title: 0 },
});

export const paragraph_body_font = createFont({
  family: 'Inter',
  weight: {
    regular: 400,
    light: 300,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    strong: 900,
    italic: 400,
  },
  size: { body: 14 },
  lineHeight: { body: 19.6 },
  letterSpacing: { body: 0 },
});

export const paragraph_font = createFont({
  family: 'Inter',
  weight: { light: 300, regular: 400, bold: 700 },
  size: { code: 14, link: 14 },
  lineHeight: { code: 14, link: 17.5 },
  letterSpacing: { code: 0, link: 0 },
});

export const text_font = createFont({
  family: 'Inter',
  weight: { regular: 400, bold: 700 },
  size: {
    '2xs': 8,
    xs: 10,
    sm: 12,
    md: 14,
    lg: 16,
    xl: 20,
    '2xl': 20,
    '3xl': 28,
    '4xl': 32,
    '5xl': 44,
    '6xl': 44,
    '7xl': 44,
    '8xl': 52,
  },
  lineHeight: {
    '2xs': 9.6,
    xs: 12,
    sm: 14.4,
    md: 16.8,
    lg: 19.2,
    xl: 24,
    '2xl': 24,
    '3xl': 33.6,
    '4xl': 38.4,
    '5xl': 52.8,
    '6xl': 52.8,
    '7xl': 52.8,
    '8xl': 62.4,
  },
  letterSpacing: {
    '2xs': 0,
    xs: 0,
    sm: 0,
    md: 0,
    lg: 0,
    xl: 0,
    '2xl': 0,
    '3xl': 0,
    '4xl': 0,
    '5xl': 0,
    '6xl': 0,
    '7xl': 0,
    '8xl': 0,
  },
});

export const label_font = createFont({
  family: 'Inter',
  weight: {
    light: 300,
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    strong: 900,
  },
  size: { small: 10, medium: 12, large: 14 },
  lineHeight: { small: 11.5, medium: 13.8, large: 16.1 },
  letterSpacing: { small: 0, medium: 0, large: 0 },
});

export const utilities_component_font = createFont({
  family: 'Roboto Mono',
  weight: { regular: '400', bold: '700' },
  size: { component: 16 },
  lineHeight: { component: 22.4 },
  letterSpacing: { component: 0 },
});

export const aggregation = {
  display: display_font,
  heading: heading_font,
  'heading.title': heading_title_font,
  'paragraph.body': paragraph_body_font,
  paragraph: paragraph_font,
  text: text_font,
  label: label_font,
  'utilities.component': utilities_component_font,
};
