import { createTamagui, createTokens, createThemes } from 'tamagui';

const size = {
  0: 0,
  1: 5,
  2: 10,
  3: 15,
  4: 20,
  true: 10,
};

const space = {
  0: 0,
  1: 5,
  2: 10,
  3: 15,
  4: 20,
  true: 10,
};

// Define all acceptable variable token names
const colors = createTokens({
  light: {
    background: '#ffffff',
    text: '#000000',
    primary: '#2196F3',
    secondary: '#FF9800',
    success: '#4CAF50',
    error: '#F44336',
    warning: '#FFC107',
    info: '#2196F3',
    muted: '#BDBDBD',
    accent: '#FFEB3B',
    border: '#E0E0E0',
    control: '#FAFAFA',
    card: '#FFFFFF',
    modal: '#FFFFFF',
    overlay: 'rgba(0, 0, 0, 0.5)',
    shadow: 'rgba(0, 0, 0, 0.12)',
    shadowLight: 'rgba(0, 0, 0, 0.05)',
    shadowDark: 'rgba(0, 0, 0, 0.2)',
    transparent: 'transparent',
    black: '#000000',
    white: '#FFFFFF',
  },
  dark: {
    background: '#121212',
    text: '#FFFFFF',
    primary: '#BBDEFB',
    secondary: '#FFE0B2',
    success: '#C8E6C9',
    error: '#FFCDD2',
    warning: '#FFD54F',
    info: '#BBDEFB',
    muted: '#616161',
    accent: '#FFF176',
    border: '#424242',
    control: '#212121',
    card: '#1E1E1E',
    modal: '#1E1E1E',
    overlay: 'rgba(255, 255, 255, 0.2)',
    shadow: 'rgba(255, 255, 255, 0.12)',
    shadowLight: 'rgba(255, 255, 255, 0.2)',
    shadowDark: 'rgba(255, 255, 255, 0.1)',
    transparent: 'transparent',
    black: '#000000',
    white: '#FFFFFF',
  },
});

// Create themes based on the color tokens
const themes = createThemes({
  light: {
    bg: colors.light.background,
    color: colors.light.text,
    primary: colors.light.primary,
    secondary: colors.light.secondary,
    success: colors.light.success,
    error: colors.light.error,
    warning: colors.light.warning,
    info: colors.light.info,
    muted: colors.light.muted,
    accent: colors.light.accent,
    border: colors.light.border,
    control: colors.light.control,
    card: colors.light.card,
    modal: colors.light.modal,
    overlay: colors.light.overlay,
    shadow: colors.light.shadow,
    shadowLight: colors.light.shadowLight,
    shadowDark: colors.light.shadowDark,
  },
  dark: {
    bg: colors.dark.background,
    color: colors.dark.text,
    primary: colors.dark.primary,
    secondary: colors.dark.secondary,
    success: colors.dark.success,
    error: colors.dark.error,
    warning: colors.dark.warning,
    info: colors.dark.info,
    muted: colors.dark.muted,
    accent: colors.dark.accent,
    border: colors.dark.border,
    control: colors.dark.control,
    card: colors.dark.card,
    modal: colors.dark.modal,
    overlay: colors.dark.overlay,
    shadow: colors.dark.shadow,
    shadowLight: colors.dark.shadowLight,
    shadowDark: colors.dark.shadowDark,
  },
});

// Create Tamagui config
const tamaguiConfig = createTamagui({
  themes,
  tokens: {
    size,
    space,
    color: colors,
    zIndex: {
      0: 0,
      1: 100,
      2: 200,
      3: 300,
      4: 400,
      5: 500,
      true: 100,
    },
    radius: {
      0: 0,
      1: 4,
      2: 8,
      3: 12,
      4: 16,
      true: 4,
    },
    font: {
      size: {
        1: 12,
        2: 14,
        3: 16,
        4: 18,
        5: 20,
        6: 24,
        7: 32,
        8: 48,
        true: 16,
      },
      weight: {
        1: '100',
        2: '200',
        3: '300',
        4: '400',
        5: '500',
        6: '600',
        7: '700',
        8: '800',
        9: '900',
        true: '400',
      },
      family: {
        heading: 'System',
        body: 'System',
      },
      lineHeight: {
        1: 16,
        2: 20,
        3: 24,
        4: 28,
        5: 32,
        6: 40,
        7: 48,
        8: 64,
        true: 24,
      },
    },
  },
  fonts: {
    body: 'System',
    heading: 'System',
  },
});

export default tamaguiConfig;
