name: Publish Packages to NPM
description: 'Publish distribution packages to NPM'
author: 'First Ledger'

inputs:
  # Node.js version to use for setting up the environment.
  node_version:
    required: false
    type: string
    description: 'NodeJS version to use'
    default: '20'

  token:
    description: 'NPM Publishing Auth Token'
    required: true

  cmd:
    type: string
    description: 'Command'
    required: true

  tag:
    type: string
    description: 'Publish Type Tag'
    required: true

  dry:
    type: string
    description: 'Denote if this is a dry run'
    required: false

runs:
  using: 'composite'
  steps:
    # Step to set up Node.js and install npm
    - name: Set up Node.js and install npm
      uses: actions/setup-node@v4
      with:
        node-version: '${{ inputs.node_version }}' # Use the Node.js version passed as input
        registry-url: 'https://registry.npmjs.org'

    - name: Publish pkg on NPM 📦
      if: ${{ inputs.dry == '' || inputs.dry == 'false' }}
      shell: bash
      run: '${{inputs.cmd}} --tag ${{inputs.tag}}'
      env:
        NODE_AUTH_TOKEN: ${{inputs.token}}

    - name: Publish pkg on NPM
      if: inputs.dry == 'true'
      shell: bash
      run: '${{inputs.cmd}} --tag ${{inputs.tag}} --dry-run'
      env:
        NODE_AUTH_TOKEN: ${{inputs.token}}
