/**
 * Do not edit directly, this file was auto-generated.
 */

export const FLDS_SIZE_SPACE_0 = '0px';
export const FLDS_SIZE_SPACE_100 = '4px';
export const FLDS_SIZE_SPACE_150 = '6px';
export const FLDS_SIZE_SPACE_200 = '8px';
export const FLDS_SIZE_SPACE_300 = '12px';
export const FLDS_SIZE_SPACE_400 = '16px';
export const FLDS_SIZE_SPACE_600 = '24px';
export const FLDS_SIZE_SPACE_800 = '32px';
export const FLDS_SIZE_SPACE_1200 = '48px';
export const FLDS_SIZE_SPACE_1600 = '64px';
export const FLDS_SIZE_SPACE_2400 = '96px';
export const FLDS_SIZE_SPACE_3000 = '128px';
export const FLDS_SIZE_SPACE_4000 = '160px';
export const FLDS_SIZE_SPACE_NEGATIVE_100 = '-4px';
export const FLDS_SIZE_SPACE_NEGATIVE_200 = '-8px';
export const FLDS_SIZE_SPACE_NEGATIVE_300 = '-12px';
export const FLDS_SIZE_SPACE_NEGATIVE_400 = '-16px';
export const FLDS_SIZE_SPACE_NEGATIVE_600 = '-24px';
export const FLDS_SIZE_SPACE_050 = '2px';
export const FLDS_SIZE_RADIUS_100 = '4px';
export const FLDS_SIZE_RADIUS_200 = '10px';
export const FLDS_SIZE_RADIUS_300 = '16px';
export const FLDS_SIZE_RADIUS_400 = '20px';
export const FLDS_SIZE_RADIUS_FULL = '9999px';
export const FLDS_SIZE_DEPTH_0 = '0px';
export const FLDS_SIZE_DEPTH_100 = '4px';
export const FLDS_SIZE_DEPTH_200 = '8px';
export const FLDS_SIZE_DEPTH_400 = '16px';
export const FLDS_SIZE_DEPTH_800 = '32px';
export const FLDS_SIZE_DEPTH_1200 = '48px';
export const FLDS_SIZE_DEPTH_025 = '1px';
export const FLDS_SIZE_DEPTH_NEGATIVE_025 = '-1px';
export const FLDS_SIZE_DEPTH_NEGATIVE_100 = '-4px';
export const FLDS_SIZE_DEPTH_NEGATIVE_200 = '-8px';
export const FLDS_SIZE_DEPTH_NEGATIVE_400 = '-16px';
export const FLDS_SIZE_DEPTH_NEGATIVE_800 = '-32px';
export const FLDS_SIZE_DEPTH_NEGATIVE_1200 = '-48px';
export const FLDS_SIZE_STROKE_BORDER = '1px';
export const FLDS_SIZE_STROKE_FOCUS_RING = '2px';
export const FLDS_SIZE_BLUR_100 = '4px';
export const FLDS_SIZE_ICON_SMALL = '24px';
export const FLDS_SIZE_ICON_MEDIUM = '32px';
export const FLDS_SIZE_ICON_LARGE = '40px';
export const FLDS_SIZE_ICON_2_X_LARGE = '80px';
export const FLDS_SIZE_ICON_X_LARGE = '60px';
export const FLDS_SIZE_ICON_3_X_LARGE = '100px';
export const FLDS_SIZE_PADDING_DESKTOP = '24px';
export const FLDS_TYPOGRAPHY_FONT_FAMILY_PRIMARY = 'Inter';
export const FLDS_TYPOGRAPHY_FONT_FAMILY_SECONDARY = 'Noto Serif';
export const FLDS_TYPOGRAPHY_FONT_FAMILY_TERTIARY = 'Roboto Mono';
export const FLDS_TYPOGRAPHY_FONT_LINE_0 = '100%';
export const FLDS_TYPOGRAPHY_FONT_LINE_1 = '105%';
export const FLDS_TYPOGRAPHY_FONT_LINE_2 = '105%';
export const FLDS_TYPOGRAPHY_FONT_LINE_3 = '115%';
export const FLDS_TYPOGRAPHY_FONT_LINE_4 = '120%';
export const FLDS_TYPOGRAPHY_FONT_LINE_5 = '175%';
export const FLDS_TYPOGRAPHY_FONT_LINE_NEGATIVE_1 = '90%';
export const FLDS_TYPOGRAPHY_FONT_SPREAD_0 = '100%';
export const FLDS_TYPOGRAPHY_FONT_SPREAD_1 = '105%';
export const FLDS_TYPOGRAPHY_FONT_SPREAD_2 = '105%';
export const FLDS_TYPOGRAPHY_FONT_SPREAD_3 = '115%';
export const FLDS_TYPOGRAPHY_FONT_SPREAD_4 = '120%';
export const FLDS_TYPOGRAPHY_FONT_SPREAD_5 = '175%';
export const FLDS_TYPOGRAPHY_FONT_SPREAD_NEGATIVE_1 = '90%';
export const FLDS_TYPOGRAPHY_FONT_SIZE_2XL = '24px'; // fontSize variable for 24
export const FLDS_TYPOGRAPHY_FONT_SIZE_XS = '10px'; // fontSize variable for 10
export const FLDS_TYPOGRAPHY_FONT_SIZE_BASE = '14px'; // fontSize variable for 14
export const FLDS_TYPOGRAPHY_FONT_SIZE_8XL = '48px'; // fontSize variable for 52
export const FLDS_TYPOGRAPHY_FONT_SIZE_10XL = '48px'; // fontSize variable for 52
export const FLDS_TYPOGRAPHY_FONT_SIZE_5XL = '36px'; // fontSize variable for 36
export const FLDS_TYPOGRAPHY_FONT_SIZE_11XL = '72px';
export const FLDS_TYPOGRAPHY_FONT_SIZE_7XL = '44px'; // fontSize variable for 44
export const FLDS_TYPOGRAPHY_FONT_SIZE_SM = '12px'; // fontSize variable for 12
export const FLDS_TYPOGRAPHY_FONT_SIZE_9XL = '48px'; // fontSize variable for 52
export const FLDS_TYPOGRAPHY_FONT_SIZE_3XL = '28px'; // fontSize variable for 28
export const FLDS_TYPOGRAPHY_FONT_SIZE_XL = '20px'; // fontSize variable for 20
export const FLDS_TYPOGRAPHY_FONT_SIZE_6XL = '40px'; // fontSize variable for 40
export const FLDS_TYPOGRAPHY_FONT_SIZE_MD = '16px'; // fontSize variable for 16
export const FLDS_TYPOGRAPHY_FONT_SIZE_LG = '18px'; // fontSize variable for 18
export const FLDS_TYPOGRAPHY_FONT_SIZE_4XL = '32px';
