/**
 * Do not edit directly, this file was auto-generated.
 */

export const WDS_COLOR_BACKGROUND_DEFAULT_PRIMARY = '#ecfeff'; // Bg/Default/Default
export const WDS_COLOR_BACKGROUND_DEFAULT_SECONDARY = '#cffafe'; // Bg/Default/Secondary
export const WDS_COLOR_BACKGROUND_DEFAULT_TERTIARY = '#a5f3fc'; // Bg/Default/Tertiary
export const WDS_COLOR_BACKGROUND_DEFAULT_PRIMARY_HOVER = '#cffafe'; // Bg/Default/Default Hover
export const WDS_COLOR_BACKGROUND_DEFAULT_SECONDARY_HOVER = '#a5f3fc'; // Bg/Default/Secondary Hover
export const WDS_COLOR_BACKGROUND_DEFAULT_TERTIARY_HOVER = '#67e8f9'; // Bg/Default/Tertiary Hover
export const WDS_COLOR_BACKGROUND_BRAND_DEFAULT = '#67e8f9'; // Bg/Brand/Default
export const WDS_COLOR_BACKGROUND_BRAND_SECONDARY = '#a5f3fc'; // Bg/Brand/Secondary
export const WDS_COLOR_BACKGROUND_BRAND_HOVER = '#06b6d4'; // Bg/Brand/Hover
export const WDS_COLOR_BACKGROUND_BRAND_SECONDARY_HOVER = '#67e8f9'; // Bg/Brand/Secondary Hover
export const WDS_COLOR_BACKGROUND_BRAND_TERTIARY = '#cffafe'; // Bg/Brand/Tertiary
export const WDS_COLOR_BACKGROUND_BRAND_TERTIARY_HOVER = '#a5f3fc'; // Bg/Brand/Tertiary Hover
export const WDS_COLOR_BACKGROUND_POSITIVE_DEFAULT = '#14ae5c'; // Bg/Positive/Default
export const WDS_COLOR_BACKGROUND_POSITIVE_SECONDARY = '#cff7d3'; // Bg/Positive/Secondary
export const WDS_COLOR_BACKGROUND_POSITIVE_HOVER = '#009951'; // Bg/Positive/Hover
export const WDS_COLOR_BACKGROUND_POSITIVE_SECONDARY_HOVER = '#aff4c6'; // Bg/Positive/Secondary Hover
export const WDS_COLOR_BACKGROUND_POSITIVE_TERTIARY = '#ebffee'; // Bg/Positive/Tertiary
export const WDS_COLOR_BACKGROUND_POSITIVE_TERTIARY_HOVER = '#cff7d3'; // Bg/Positive/Tertiary Hover
export const WDS_COLOR_BACKGROUND_WARNING_DEFAULT = '#e8b931'; // Bg/Warning/Default
export const WDS_COLOR_BACKGROUND_WARNING_SECONDARY = '#ffe8a3'; // Bg/Warning/Secondary
export const WDS_COLOR_BACKGROUND_WARNING_HOVER = '#e5a000'; // Bg/Warning/Hover
export const WDS_COLOR_BACKGROUND_WARNING_SECONDARY_HOVER = '#e8b931'; // Bg/Warning/Secondary Hover
export const WDS_COLOR_BACKGROUND_WARNING_TERTIARY = '#fff1c2'; // Bg/Warning/Tertiary
export const WDS_COLOR_BACKGROUND_WARNING_TERTIARY_HOVER = '#ffe8a3'; // Bg/Warning/Tertiary Hover
export const WDS_COLOR_BACKGROUND_DANGER_DEFAULT = '#f03330'; // Bg/Danger/Default
export const WDS_COLOR_BACKGROUND_DANGER_SECONDARY = '#fdd3d0'; // Bg/Danger/Secondary
export const WDS_COLOR_BACKGROUND_DANGER_HOVER = '#d21e1e'; // Bg/Danger/Hover
export const WDS_COLOR_BACKGROUND_DANGER_SECONDARY_HOVER = '#fcb3ad'; // Bg/Danger/Secondary Hover
export const WDS_COLOR_BACKGROUND_DANGER_TERTIARY = '#fee9e7'; // Bg/Danger/Tertiary
export const WDS_COLOR_BACKGROUND_DANGER_TERTIARY_HOVER = '#fdd3d0'; // Bg/Danger/Tertiary Hover
export const WDS_COLOR_BACKGROUND_DISABLED_DEFAULT = '#b3b3b3'; // Bg/Disabled/Default
export const WDS_COLOR_BACKGROUND_UTILITIES_SCRIM = '#ffffff'; // Bg/Utilities/Scrim
export const WDS_COLOR_BACKGROUND_UTILITIES_OVERLAY = '#000000'; // Bg/Utilities/Overlay
export const WDS_COLOR_BACKGROUND_UTILITIES_BLANKET = '#000000'; // Bg/Utilities/Blanket
export const WDS_COLOR_BACKGROUND_UTILITIES_MEASUREMENT = '#fbcfe8'; // Bg/Utilities/Measurement
export const WDS_COLOR_BACKGROUND_UTILITIES_HIGHLIGHT = '#0c0c0d';
export const WDS_COLOR_BACKGROUND_UTILITIES_HIGHLIGHT_2 = '#0c0c0d';
export const WDS_COLOR_BACKGROUND_UTILITIES_HIGHLIGHT_BRAND = '#87a5ff';
export const WDS_COLOR_BACKGROUND_UTILITIES_HIGHLIGHT_BRAND_2 = '#456eeb';
export const WDS_COLOR_BACKGROUND_UTILITIES_HIGHLIGHT_BRAND_3 = '#456eeb';
export const WDS_COLOR_BACKGROUND_UTILITIES_HIGHLIGHT_BRAND_4 = '#456eeb';
export const WDS_COLOR_BACKGROUND_NEUTRAL_DEFAULT = '#5a5a5a'; // Bg/Neutral/Default
export const WDS_COLOR_BACKGROUND_NEUTRAL_HOVER = '#434343'; // Bg/Neutral/Hover
export const WDS_COLOR_BACKGROUND_NEUTRAL_SECONDARY = '#cdcdcd'; // Bg/Neutral/Secondary
export const WDS_COLOR_BACKGROUND_NEUTRAL_SECONDARY_HOVER = '#b2b2b2'; // Bg/Neutral/Secondary Hover
export const WDS_COLOR_BACKGROUND_NEUTRAL_TERTIARY = '#e3e3e3'; // Bg/Neutral/Tertiary
export const WDS_COLOR_BACKGROUND_NEUTRAL_TERTIARY_HOVER = '#cdcdcd'; // Bg/Neutral/Tertiary Hover
export const WDS_COLOR_BACKGROUND_NEUTRAL_SECONDARY_2 = '#cdcdcd'; // Bg/Neutral/Secondary
export const WDS_COLOR_BACKGROUND_BOLD_DEFAULT = '#ffffff'; // Bg/Default/Default
export const WDS_COLOR_BACKGROUND_BOLD_DEFAULT_HOVER = '#f5f5f5'; // Bg/Default/Default Hover
export const WDS_COLOR_BACKGROUND_BOLD_SECONDARY = '#f5f5f5'; // Bg/Default/Secondary
export const WDS_COLOR_BACKGROUND_BOLD_SECONDARY_HOVER = '#e6e6e6'; // Bg/Default/Secondary Hover
export const WDS_COLOR_BACKGROUND_BOLD_TERTIARY = '#d9d9d9'; // Bg/Default/Tertiary
export const WDS_COLOR_BACKGROUND_BOLD_TERTIARY_HOVER = '#b3b3b3'; // Bg/Default/Tertiary Hover
export const WDS_COLOR_BACKGROUND_BOLD_TRANSPARENT = '#ffffff'; // Bg/Default/Tertiary Hover
export const WDS_COLOR_BACKGROUND_ACCENT_DEFAULT = '#0d9488'; // Bg/Brand/Default
export const WDS_COLOR_BACKGROUND_ACCENT_HOVER = '#0f766e'; // Bg/Brand/Hover
export const WDS_COLOR_BACKGROUND_ACCENT_SECONDARY = '#5eead4'; // Bg/Brand/Secondary
export const WDS_COLOR_BACKGROUND_ACCENT_SECONDARY_HOVER = '#2dd4bf'; // Bg/Brand/Secondary Hover
export const WDS_COLOR_BACKGROUND_ACCENT_TERTIARY = '#99f6e4'; // Bg/Brand/Tertiary
export const WDS_COLOR_BACKGROUND_ACCENT_TERTIARY_HOVER = '#5eead4'; // Bg/Brand/Tertiary Hover
export const WDS_COLOR_BACKGROUND_INVERT_DEFAULT = '#164e63'; // Bg/Default/Default
export const WDS_COLOR_BACKGROUND_INVERT_DEFAULT_HOVER = '#164e63'; // Bg/Default/Default Hover
export const WDS_COLOR_BACKGROUND_INVERT_SECONDARY = '#164e63'; // Bg/Default/Secondary
export const WDS_COLOR_BACKGROUND_INVERT_SECONDARY_HOVER = '#155e75'; // Bg/Default/Secondary Hover
export const WDS_COLOR_BACKGROUND_INVERT_TERTIARY = '#0e7490'; // Bg/Default/Tertiary
export const WDS_COLOR_BACKGROUND_INVERT_TERTIARY_HOVER = '#0891b2'; // Bg/Default/Tertiary Hover
export const WDS_COLOR_TEXT_DEFAULT_PRIMARY = '#1e1e1e';
export const WDS_COLOR_TEXT_DEFAULT_SECONDARY = '#757575';
export const WDS_COLOR_TEXT_DEFAULT_TERTIARY = '#b3b3b3';
export const WDS_COLOR_TEXT_BRAND_DEFAULT = '#155e75';
export const WDS_COLOR_TEXT_BRAND_SECONDARY = '#0891b2';
export const WDS_COLOR_TEXT_BRAND_TERTIARY = '#06b6d4';
export const WDS_COLOR_TEXT_BRAND_ON_BRAND = '#cffafe';
export const WDS_COLOR_TEXT_BRAND_ON_BRAND_SECONDARY = '#155e75';
export const WDS_COLOR_TEXT_BRAND_ON_BRAND_TERTIARY = '#0e7490';
export const WDS_COLOR_TEXT_POSITIVE_DEFAULT = '#02542d';
export const WDS_COLOR_TEXT_POSITIVE_SECONDARY = '#009951';
export const WDS_COLOR_TEXT_POSITIVE_TERTIARY = '#14ae5c';
export const WDS_COLOR_TEXT_POSITIVE_ON_POSITIVE = '#ebffee';
export const WDS_COLOR_TEXT_POSITIVE_ON_POSITIVE_SECONDARY = '#02542d';
export const WDS_COLOR_TEXT_POSITIVE_ON_POSITIVE_TERTIARY = '#02542d';
export const WDS_COLOR_TEXT_WARNING_DEFAULT = '#975102';
export const WDS_COLOR_TEXT_WARNING_SECONDARY = '#bf6a02';
export const WDS_COLOR_TEXT_WARNING_TERTIARY = '#e5a000';
export const WDS_COLOR_TEXT_WARNING_ON_WARNING = '#401b01';
export const WDS_COLOR_TEXT_WARNING_ON_WARNING_SECONDARY = '#682d03';
export const WDS_COLOR_TEXT_WARNING_ON_WARNING_TERTIARY = '#401b01';
export const WDS_COLOR_TEXT_DANGER_DEFAULT = '#9c120f';
export const WDS_COLOR_TEXT_DANGER_SECONDARY = '#d21e1e';
export const WDS_COLOR_TEXT_DANGER_TERTIARY = '#f03330';
export const WDS_COLOR_TEXT_DANGER_ON_DANGER = '#fee9e7';
export const WDS_COLOR_TEXT_DANGER_ON_DANGER_SECONDARY = '#9c120f';
export const WDS_COLOR_TEXT_DANGER_ON_DANGER_TERTIARY = '#9c120f';
export const WDS_COLOR_TEXT_DISABLED_DEFAULT = '#e6e6e6';
export const WDS_COLOR_TEXT_DISABLED_ON_DISABLED = '#d9d9d9';
export const WDS_COLOR_TEXT_UTILITIES_TEXT_ON_OVERLAY = '#0c0c0d';
export const WDS_COLOR_TEXT_UTILITIES_TEXT_ON_MEASUREMENT = '#9d174d';
export const WDS_COLOR_TEXT_NEUTRAL_DEFAULT = '#303030';
export const WDS_COLOR_TEXT_NEUTRAL_SECONDARY = '#434343';
export const WDS_COLOR_TEXT_NEUTRAL_TERTIARY = '#5a5a5a';
export const WDS_COLOR_TEXT_NEUTRAL_ON_NEUTRAL = '#f3f3f3';
export const WDS_COLOR_TEXT_NEUTRAL_ON_NEUTRAL_SECONDARY = '#303030';
export const WDS_COLOR_TEXT_NEUTRAL_ON_NEUTRAL_TERTIARY = '#434343';
export const WDS_COLOR_TEXT_INVERT_DEFAULT = '#ffffff';
export const WDS_COLOR_TEXT_INVERT_SECONDARY = '#ffffff';
export const WDS_COLOR_TEXT_INVERT_TERTIARY = '#ffffff';
export const WDS_COLOR_ICON_DEFAULT_PRIMARY = '#1e1e1e';
export const WDS_COLOR_ICON_DEFAULT_SECONDARY = '#757575';
export const WDS_COLOR_ICON_DEFAULT_TERTIARY = '#b3b3b3';
export const WDS_COLOR_ICON_BRAND_DEFAULT = '#155e75';
export const WDS_COLOR_ICON_BRAND_SECONDARY = '#0891b2';
export const WDS_COLOR_ICON_BRAND_TERTIARY = '#06b6d4';
export const WDS_COLOR_ICON_BRAND_ON_BRAND = '#cffafe';
export const WDS_COLOR_ICON_BRAND_ON_BRAND_SECONDARY = '#164e63';
export const WDS_COLOR_ICON_BRAND_ON_BRAND_TERTIARY = '#155e75';
export const WDS_COLOR_ICON_POSITIVE_DEFAULT = '#02542d';
export const WDS_COLOR_ICON_POSITIVE_SECONDARY = '#009951';
export const WDS_COLOR_ICON_POSITIVE_TERTIARY = '#14ae5c';
export const WDS_COLOR_ICON_POSITIVE_ON_POSITIVE = '#ebffee';
export const WDS_COLOR_ICON_POSITIVE_ON_POSITIVE_SECONDARY = '#02542d';
export const WDS_COLOR_ICON_POSITIVE_ON_POSITIVE_TERTIARY = '#024023';
export const WDS_COLOR_ICON_WARNING_DEFAULT = '#975102';
export const WDS_COLOR_ICON_WARNING_SECONDARY = '#bf6a02';
export const WDS_COLOR_ICON_WARNING_TERTIARY = '#e5a000';
export const WDS_COLOR_ICON_WARNING_ON_WARNING = '#401b01';
export const WDS_COLOR_ICON_WARNING_ON_WARNING_SECONDARY = '#682d03';
export const WDS_COLOR_ICON_WARNING_ON_WARNING_TERTIARY = '#522504';
export const WDS_COLOR_ICON_DANGER_DEFAULT = '#9c120f';
export const WDS_COLOR_ICON_DANGER_SECONDARY = '#d21e1e';
export const WDS_COLOR_ICON_DANGER_TERTIARY = '#f03330';
export const WDS_COLOR_ICON_DANGER_ON_DANGER = '#fee9e7';
export const WDS_COLOR_ICON_DANGER_ON_DANGER_SECONDARY = '#9c120f';
export const WDS_COLOR_ICON_DANGER_ON_DANGER_TERTIARY = '#9c120f';
export const WDS_COLOR_ICON_DISABLED_DEFAULT = '#e6e6e6';
export const WDS_COLOR_ICON_DISABLED_ON_DISABLED = '#d9d9d9';
export const WDS_COLOR_ICON_NEUTRAL_DEFAULT = '#303030';
export const WDS_COLOR_ICON_NEUTRAL_SECONDARY = '#5a5a5a';
export const WDS_COLOR_ICON_NEUTRAL_TERTIARY = '#767676';
export const WDS_COLOR_ICON_NEUTRAL_ON_NEUTRAL = '#f3f3f3';
export const WDS_COLOR_ICON_NEUTRAL_ON_NEUTRAL_SECONDARY = '#303030';
export const WDS_COLOR_ICON_NEUTRAL_ON_NEUTRAL_TERTIARY = '#434343';
export const WDS_COLOR_ICON_UTILITIES_ICON_ON_MEASUREMENT = '#9d174d';
export const WDS_COLOR_ICON_UTILITIES_ICON = '#db2777';
export const WDS_COLOR_BORDER_DEFAULT_PRIMARY = '#67e8f9';
export const WDS_COLOR_BORDER_DEFAULT_SECONDARY = '#06b6d4';
export const WDS_COLOR_BORDER_DEFAULT_TERTIARY = '#06b6d4';
export const WDS_COLOR_BORDER_BRAND_DEFAULT = '#06b6d4';
export const WDS_COLOR_BORDER_BRAND_SECONDARY = '#06b6d4';
export const WDS_COLOR_BORDER_BRAND_TERTIARY = '#67e8f9';
export const WDS_COLOR_BORDER_POSITIVE_DEFAULT = '#02542d';
export const WDS_COLOR_BORDER_POSITIVE_SECONDARY = '#009951';
export const WDS_COLOR_BORDER_POSITIVE_TERTIARY = '#14ae5c';
export const WDS_COLOR_BORDER_WARNING_DEFAULT = '#975102';
export const WDS_COLOR_BORDER_WARNING_SECONDARY = '#bf6a02';
export const WDS_COLOR_BORDER_WARNING_TERTIARY = '#e5a000';
export const WDS_COLOR_BORDER_DANGER_DEFAULT = '#9c120f';
export const WDS_COLOR_BORDER_DANGER_SECONDARY = '#d21e1e';
export const WDS_COLOR_BORDER_DANGER_TERTIARY = '#f03330';
export const WDS_COLOR_BORDER_DISABLED_DEFAULT = '#d9d9d9';
export const WDS_COLOR_BORDER_UTILITIES_MEASUREMENT = '#f472b6';
export const WDS_COLOR_BORDER_UTILITIES_SWATCH = '#000000';
export const WDS_COLOR_BORDER_NEUTRAL_DEFAULT = '#303030';
export const WDS_COLOR_BORDER_NEUTRAL_SECONDARY = '#767676';
export const WDS_COLOR_BORDER_NEUTRAL_TERTIARY = '#b2b2b2';
export const WDS_COLOR_OVERLAY_WHITE_WHITE4 = '#ffffff';
export const WDS_MODALS_TOMATO_TOMATO10 = '#db4324';
export const WDS_MODALS_TOMATO_TOMATO7 = '#f3b0a2';
export const WDS_MODALS_TOMATO_TOMATO6 = '#fac7be';
export const WDS_MODALS_TOMATO_TOMATO5 = '#fdd8d3';
export const WDS_MODALS_TOMATO_TOMATO12 = '#341711';
export const WDS_MODALS_TOMATO_TOMATO11 = '#ca3214';
export const WDS_MODALS_TOMATO_TOMATO9 = '#e54d2e';
export const WDS_MODALS_TOMATO_TOMATO3 = '#fff0ee';
export const WDS_MODALS_TOMATO_TOMATO8 = '#ea9280';
export const WDS_MODALS_TOMATO_TOMATO2 = '#fff8f7';
export const WDS_MODALS_TOMATO_TOMATO4 = '#ffe6e2';
export const WDS_MODALS_TOMATO_TOMATO1 = '#fffcfc';
export const WDS_MODALS_RED_RED4 = '#ffe5e5';
export const WDS_MODALS_RED_RED5 = '#fdd8d8';
export const WDS_MODALS_RED_RED9 = '#e5484d';
export const WDS_MODALS_RED_RED8 = '#eb9091';
export const WDS_MODALS_RED_RED12 = '#381316';
export const WDS_MODALS_RED_RED6 = '#f9c6c6';
export const WDS_MODALS_RED_RED3 = '#ffefef';
export const WDS_MODALS_RED_RED1 = '#fffcfc';
export const WDS_MODALS_RED_RED2 = '#fff8f8';
export const WDS_MODALS_RED_RED7 = '#f3aeaf';
export const WDS_MODALS_RED_RED10 = '#dc3d43';
export const WDS_MODALS_RED_RED11 = '#cd2b31';
export const WDS_MODALS_VIOLET_VIOLET10 = '#644fc1';
export const WDS_MODALS_VIOLET_VIOLET12 = '#20134b';
export const WDS_MODALS_VIOLET_VIOLET9 = '#6e56cf';
export const WDS_MODALS_VIOLET_VIOLET3 = '#f5f2ff';
export const WDS_MODALS_VIOLET_VIOLET4 = '#ede9fe';
export const WDS_MODALS_VIOLET_VIOLET8 = '#aa99ec';
export const WDS_MODALS_VIOLET_VIOLET1 = '#fdfcfe';
export const WDS_MODALS_VIOLET_VIOLET7 = '#c4b8f3';
export const WDS_MODALS_VIOLET_VIOLET6 = '#d7cff9';
export const WDS_MODALS_VIOLET_VIOLET5 = '#e4defc';
export const WDS_MODALS_VIOLET_VIOLET11 = '#5746af';
export const WDS_MODALS_VIOLET_VIOLET2 = '#fbfaff';
export const WDS_MODALS_INDIGO_INDIGO10 = '#3a5ccc';
export const WDS_MODALS_INDIGO_INDIGO8 = '#8da4ef';
export const WDS_MODALS_INDIGO_INDIGO7 = '#aec0f5';
export const WDS_MODALS_INDIGO_INDIGO2 = '#f8faff';
export const WDS_MODALS_INDIGO_INDIGO9 = '#3e63dd';
export const WDS_MODALS_INDIGO_INDIGO3 = '#f0f4ff';
export const WDS_MODALS_INDIGO_INDIGO6 = '#c6d4f9';
export const WDS_MODALS_INDIGO_INDIGO5 = '#d9e2fc';
export const WDS_MODALS_INDIGO_INDIGO12 = '#101d46';
export const WDS_MODALS_INDIGO_INDIGO4 = '#e6edfe';
export const WDS_MODALS_INDIGO_INDIGO11 = '#3451b2';
export const WDS_MODALS_INDIGO_INDIGO1 = '#fdfdfe';
export const WDS_MODALS_BLUE_BLUE7 = '#96c7f2';
export const WDS_MODALS_BLUE_BLUE9 = '#0091ff';
export const WDS_MODALS_BLUE_BLUE6 = '#b7d9f8';
export const WDS_MODALS_BLUE_BLUE5 = '#cee7fe';
export const WDS_MODALS_BLUE_BLUE4 = '#e1f0ff';
export const WDS_MODALS_BLUE_BLUE10 = '#0081f1';
export const WDS_MODALS_BLUE_BLUE8 = '#5eb0ef';
export const WDS_MODALS_BLUE_BLUE2 = '#f5faff';
export const WDS_MODALS_BLUE_BLUE3 = '#edf6ff';
export const WDS_MODALS_BLUE_BLUE11 = '#006adc';
export const WDS_MODALS_BLUE_BLUE12 = '#00254d';
export const WDS_MODALS_BLUE_BLUE1 = '#fbfdff';
export const WDS_MODALS_CYAN_CYAN10 = '#0894b3';
export const WDS_MODALS_CYAN_CYAN8 = '#3db9cf';
export const WDS_MODALS_CYAN_CYAN7 = '#84cdda';
export const WDS_MODALS_CYAN_CYAN2 = '#f2fcfd';
export const WDS_MODALS_CYAN_CYAN4 = '#d8f3f6';
export const WDS_MODALS_CYAN_CYAN5 = '#c4eaef';
export const WDS_MODALS_CYAN_CYAN12 = '#04313c';
export const WDS_MODALS_CYAN_CYAN9 = '#05a2c2';
export const WDS_MODALS_CYAN_CYAN3 = '#e7f9fb';
export const WDS_MODALS_CYAN_CYAN6 = '#aadee6';
export const WDS_MODALS_CYAN_CYAN11 = '#0c7792';
export const WDS_MODALS_CYAN_CYAN1 = '#fafdfe';
export const WDS_MODALS_TEAL_TEAL9 = '#12a594';
export const WDS_MODALS_TEAL_TEAL7 = '#8dcec3';
export const WDS_MODALS_TEAL_TEAL5 = '#c7ebe5';
export const WDS_MODALS_TEAL_TEAL4 = '#d9f3ee';
export const WDS_MODALS_TEAL_TEAL10 = '#0e9888';
export const WDS_MODALS_TEAL_TEAL3 = '#e7f9f5';
export const WDS_MODALS_TEAL_TEAL8 = '#53b9ab';
export const WDS_MODALS_TEAL_TEAL6 = '#afdfd7';
export const WDS_MODALS_TEAL_TEAL1 = '#fafefd';
export const WDS_MODALS_TEAL_TEAL12 = '#10302b';
export const WDS_MODALS_TEAL_TEAL11 = '#067a6f';
export const WDS_MODALS_TEAL_TEAL2 = '#f1fcfa';
export const WDS_MODALS_GREEN_GREEN9 = '#30a46c';
export const WDS_MODALS_GREEN_GREEN10 = '#299764';
export const WDS_MODALS_GREEN_GREEN7 = '#92ceac';
export const WDS_MODALS_GREEN_GREEN12 = '#153226';
export const WDS_MODALS_GREEN_GREEN6 = '#b4dfc4';
export const WDS_MODALS_GREEN_GREEN5 = '#ccebd7';
export const WDS_MODALS_GREEN_GREEN11 = '#18794e';
export const WDS_MODALS_GREEN_GREEN4 = '#ddf3e4';
export const WDS_MODALS_GREEN_GREEN3 = '#e9f9ee';
export const WDS_MODALS_GREEN_GREEN8 = '#5bb98c';
export const WDS_MODALS_GREEN_GREEN2 = '#f2fcf5';
export const WDS_MODALS_GREEN_GREEN1 = '#fbfefc';
export const WDS_MODALS_GRASS_GRASS10 = '#3d9a50';
export const WDS_MODALS_GRASS_GRASS6 = '#b7dfba';
export const WDS_MODALS_GRASS_GRASS9 = '#46a758';
export const WDS_MODALS_GRASS_GRASS8 = '#65ba75';
export const WDS_MODALS_GRASS_GRASS12 = '#1b311e';
export const WDS_MODALS_GRASS_GRASS5 = '#ceebcf';
export const WDS_MODALS_GRASS_GRASS7 = '#97cf9c';
export const WDS_MODALS_GRASS_GRASS4 = '#dff3df';
export const WDS_MODALS_GRASS_GRASS3 = '#ebf9eb';
export const WDS_MODALS_GRASS_GRASS2 = '#f3fcf3';
export const WDS_MODALS_GRASS_GRASS1 = '#fbfefb';
export const WDS_MODALS_GRASS_GRASS11 = '#297c3b';
export const WDS_MODALS_ORANGE_ORANGE10 = '#ed5f00';
export const WDS_MODALS_ORANGE_ORANGE9 = '#f76808';
export const WDS_MODALS_ORANGE_ORANGE11 = '#bd4b00';
export const WDS_MODALS_ORANGE_ORANGE8 = '#fa934e';
export const WDS_MODALS_ORANGE_ORANGE2 = '#fef8f4';
export const WDS_MODALS_ORANGE_ORANGE7 = '#ffb381';
export const WDS_MODALS_ORANGE_ORANGE4 = '#ffe8d7';
export const WDS_MODALS_ORANGE_ORANGE12 = '#451e11';
export const WDS_MODALS_ORANGE_ORANGE5 = '#ffdcc3';
export const WDS_MODALS_ORANGE_ORANGE3 = '#fff1e7';
export const WDS_MODALS_ORANGE_ORANGE6 = '#ffcca7';
export const WDS_MODALS_ORANGE_ORANGE1 = '#fefcfb';
export const WDS_MODALS_BROWN_BROWN10 = '#a07653';
export const WDS_MODALS_BROWN_BROWN9 = '#ad7f58';
export const WDS_MODALS_BROWN_BROWN7 = '#ddb896';
export const WDS_MODALS_BROWN_BROWN6 = '#e8cdb5';
export const WDS_MODALS_BROWN_BROWN5 = '#efddcc';
export const WDS_MODALS_BROWN_BROWN1 = '#fefdfc';
export const WDS_MODALS_BROWN_BROWN12 = '#3f2c22';
export const WDS_MODALS_BROWN_BROWN2 = '#fcf9f6';
export const WDS_MODALS_BROWN_BROWN3 = '#f8f1ea';
export const WDS_MODALS_BROWN_BROWN8 = '#d09e72';
export const WDS_MODALS_BROWN_BROWN4 = '#f4e9dd';
export const WDS_MODALS_BROWN_BROWN11 = '#886349';
export const WDS_MODALS_SKY_SKY10 = '#5fd4f4';
export const WDS_MODALS_SKY_SKY8 = '#2ebde5';
export const WDS_MODALS_SKY_SKY12 = '#003242';
export const WDS_MODALS_SKY_SKY7 = '#79cfea';
export const WDS_MODALS_SKY_SKY6 = '#a4dff1';
export const WDS_MODALS_SKY_SKY11 = '#0078a1';
export const WDS_MODALS_SKY_SKY5 = '#c1ecf9';
export const WDS_MODALS_SKY_SKY3 = '#e4f9ff';
export const WDS_MODALS_SKY_SKY9 = '#68ddfd';
export const WDS_MODALS_SKY_SKY1 = '#f9feff';
export const WDS_MODALS_SKY_SKY2 = '#f1fcff';
export const WDS_MODALS_SKY_SKY4 = '#d5f4fd';
export const WDS_MODALS_MINT_MINT10 = '#69d9c1';
export const WDS_MODALS_MINT_MINT12 = '#09342e';
export const WDS_MODALS_MINT_MINT3 = '#e1fbf4';
export const WDS_MODALS_MINT_MINT8 = '#40c4aa';
export const WDS_MODALS_MINT_MINT7 = '#7dd4c0';
export const WDS_MODALS_MINT_MINT6 = '#a5e4d4';
export const WDS_MODALS_MINT_MINT4 = '#d2f7ed';
export const WDS_MODALS_MINT_MINT11 = '#147d6f';
export const WDS_MODALS_MINT_MINT9 = '#70e1c8';
export const WDS_MODALS_MINT_MINT5 = '#c0efe3';
export const WDS_MODALS_MINT_MINT2 = '#effefa';
export const WDS_MODALS_MINT_MINT1 = '#f9fefd';
export const WDS_MODALS_LIME_LIME9 = '#99d52a';
export const WDS_MODALS_LIME_LIME4 = '#e4f7c7';
export const WDS_MODALS_LIME_LIME8 = '#94ba2c';
export const WDS_MODALS_LIME_LIME10 = '#93c926';
export const WDS_MODALS_LIME_LIME11 = '#5d770d';
export const WDS_MODALS_LIME_LIME7 = '#b1d16a';
export const WDS_MODALS_LIME_LIME6 = '#c9e894';
export const WDS_MODALS_LIME_LIME5 = '#d7f2b0';
export const WDS_MODALS_LIME_LIME12 = '#263209';
export const WDS_MODALS_LIME_LIME2 = '#f7fcf0';
export const WDS_MODALS_LIME_LIME3 = '#eefadc';
export const WDS_MODALS_LIME_LIME1 = '#fcfdfa';
export const WDS_MODALS_YELLOW_YELLOW10 = '#f7ce00';
export const WDS_MODALS_YELLOW_YELLOW4 = '#fff8bb';
export const WDS_MODALS_YELLOW_YELLOW9 = '#f5d90a';
export const WDS_MODALS_YELLOW_YELLOW2 = '#fffce8';
export const WDS_MODALS_YELLOW_YELLOW8 = '#ebbc00';
export const WDS_MODALS_YELLOW_YELLOW7 = '#efd36c';
export const WDS_MODALS_YELLOW_YELLOW5 = '#fef2a4';
export const WDS_MODALS_YELLOW_YELLOW1 = '#fdfdf9';
export const WDS_MODALS_YELLOW_YELLOW3 = '#fffbd1';
export const WDS_MODALS_YELLOW_YELLOW12 = '#35290f';
export const WDS_MODALS_YELLOW_YELLOW6 = '#f9e68c';
export const WDS_MODALS_YELLOW_YELLOW11 = '#946800';
export const WDS_MODALS_AMBER_AMBER10 = '#ffa01c';
export const WDS_MODALS_AMBER_AMBER9 = '#ffb224';
export const WDS_MODALS_AMBER_AMBER6 = '#ffd386';
export const WDS_MODALS_AMBER_AMBER11 = '#ad5700';
export const WDS_MODALS_AMBER_AMBER7 = '#f3ba63';
export const WDS_MODALS_AMBER_AMBER4 = '#ffecbc';
export const WDS_MODALS_AMBER_AMBER5 = '#ffe3a2';
export const WDS_MODALS_AMBER_AMBER1 = '#fefdfb';
export const WDS_MODALS_AMBER_AMBER12 = '#4e2009';
export const WDS_MODALS_AMBER_AMBER8 = '#ee9d2b';
export const WDS_MODALS_AMBER_AMBER2 = '#fff9ed';
export const WDS_MODALS_AMBER_AMBER3 = '#fff4d5';
export const WDS_MODALS_GRAY_GRAY10 = '#858585';
export const WDS_MODALS_GRAY_GRAY9 = '#8f8f8f';
export const WDS_MODALS_GRAY_GRAY8 = '#c7c7c7';
export const WDS_MODALS_GRAY_GRAY7 = '#dbdbdb';
export const WDS_MODALS_GRAY_GRAY5 = '#e8e8e8';
export const WDS_MODALS_GRAY_GRAY3 = '#f3f3f3';
export const WDS_MODALS_GRAY_GRAY1 = '#fcfcfc';
export const WDS_MODALS_GRAY_GRAY12 = '#171717';
export const WDS_MODALS_GRAY_GRAY11 = '#6f6f6f';
export const WDS_MODALS_GRAY_GRAY6 = '#e2e2e2';
export const WDS_MODALS_GRAY_GRAY4 = '#ededed';
export const WDS_MODALS_GRAY_GRAY2 = '#f8f8f8';
export const WDS_MODALS_MAUVE_MAUVE10 = '#86848d';
export const WDS_MODALS_MAUVE_MAUVE7 = '#dcdbdd';
export const WDS_MODALS_MAUVE_MAUVE5 = '#e9e8ea';
export const WDS_MODALS_MAUVE_MAUVE8 = '#c8c7cb';
export const WDS_MODALS_MAUVE_MAUVE6 = '#e4e2e4';
export const WDS_MODALS_MAUVE_MAUVE4 = '#eeedef';
export const WDS_MODALS_MAUVE_MAUVE1 = '#fdfcfd';
export const WDS_MODALS_MAUVE_MAUVE12 = '#1a1523';
export const WDS_MODALS_MAUVE_MAUVE11 = '#6f6e77';
export const WDS_MODALS_MAUVE_MAUVE2 = '#f9f8f9';
export const WDS_MODALS_MAUVE_MAUVE9 = '#908e96';
export const WDS_MODALS_MAUVE_MAUVE3 = '#f4f2f4';
export const WDS_MODALS_SLATE_SLATE6 = '#dfe3e6';
export const WDS_MODALS_SLATE_SLATE9 = '#889096';
export const WDS_MODALS_SLATE_SLATE4 = '#eceef0';
export const WDS_MODALS_SLATE_SLATE7 = '#d7dbdf';
export const WDS_MODALS_SLATE_SLATE8 = '#c1c8cd';
export const WDS_MODALS_SLATE_SLATE5 = '#e6e8eb';
export const WDS_MODALS_SLATE_SLATE10 = '#7e868c';
export const WDS_MODALS_SLATE_SLATE1 = '#fbfcfd';
export const WDS_MODALS_SLATE_SLATE11 = '#687076';
export const WDS_MODALS_SLATE_SLATE2 = '#f8f9fa';
export const WDS_MODALS_SLATE_SLATE3 = '#f1f3f5';
export const WDS_MODALS_SLATE_SLATE12 = '#11181c';
export const WDS_MODALS_SAGE_SAGE7 = '#d7dcda';
export const WDS_MODALS_SAGE_SAGE6 = '#dfe4e2';
export const WDS_MODALS_SAGE_SAGE3 = '#f1f4f3';
export const WDS_MODALS_SAGE_SAGE11 = '#6a716e';
export const WDS_MODALS_SAGE_SAGE9 = '#8a918e';
export const WDS_MODALS_SAGE_SAGE5 = '#e6e9e8';
export const WDS_MODALS_SAGE_SAGE10 = '#808784';
export const WDS_MODALS_SAGE_SAGE4 = '#ecefed';
export const WDS_MODALS_SAGE_SAGE1 = '#fbfdfc';
export const WDS_MODALS_SAGE_SAGE12 = '#111c18';
export const WDS_MODALS_SAGE_SAGE8 = '#c2c9c6';
export const WDS_MODALS_SAGE_SAGE2 = '#f8faf9';
export const WDS_MODALS_OLIVE_OLIVE10 = '#818780';
export const WDS_MODALS_OLIVE_OLIVE8 = '#c3c8c2';
export const WDS_MODALS_OLIVE_OLIVE6 = '#e0e4e0';
export const WDS_MODALS_OLIVE_OLIVE1 = '#fcfdfc';
export const WDS_MODALS_OLIVE_OLIVE9 = '#8b918a';
export const WDS_MODALS_OLIVE_OLIVE5 = '#e6e9e6';
export const WDS_MODALS_OLIVE_OLIVE4 = '#ecefec';
export const WDS_MODALS_OLIVE_OLIVE3 = '#f2f4f2';
export const WDS_MODALS_OLIVE_OLIVE12 = '#141e12';
export const WDS_MODALS_OLIVE_OLIVE11 = '#6b716a';
export const WDS_MODALS_OLIVE_OLIVE7 = '#d8dcd8';
export const WDS_MODALS_OLIVE_OLIVE2 = '#f8faf8';
export const WDS_MODALS_SAND_SAND10 = '#868682';
export const WDS_MODALS_SAND_SAND6 = '#e3e3e0';
export const WDS_MODALS_SAND_SAND4 = '#eeeeec';
export const WDS_MODALS_SAND_SAND9 = '#90908c';
export const WDS_MODALS_SAND_SAND7 = '#dbdbd7';
export const WDS_MODALS_SAND_SAND5 = '#e9e9e6';
export const WDS_MODALS_SAND_SAND12 = '#1b1b18';
export const WDS_MODALS_SAND_SAND2 = '#f9f9f8';
export const WDS_MODALS_SAND_SAND11 = '#706f6c';
export const WDS_MODALS_SAND_SAND3 = '#f3f3f2';
export const WDS_MODALS_SAND_SAND8 = '#c8c7c1';
export const WDS_MODALS_SAND_SAND1 = '#fdfdfc';
export const WDS_MODALS_GOLD_GOLD7 = '#cbbda4';
export const WDS_MODALS_GOLD_GOLD8 = '#b8a383';
export const WDS_MODALS_GOLD_GOLD6 = '#dad1bd';
export const WDS_MODALS_GOLD_GOLD5 = '#e5dfd0';
export const WDS_MODALS_GOLD_GOLD4 = '#eeeadd';
export const WDS_MODALS_GOLD_GOLD10 = '#8c795d';
export const WDS_MODALS_GOLD_GOLD1 = '#fdfdfc';
export const WDS_MODALS_GOLD_GOLD9 = '#978365';
export const WDS_MODALS_GOLD_GOLD3 = '#f5f2e9';
export const WDS_MODALS_GOLD_GOLD12 = '#3b352b';
export const WDS_MODALS_GOLD_GOLD11 = '#776750';
export const WDS_MODALS_GOLD_GOLD2 = '#fbf9f2';
export const WDS_MODALS_BRONZE_BRONZE10 = '#977669';
export const WDS_MODALS_BRONZE_BRONZE1 = '#fdfcfc';
export const WDS_MODALS_BRONZE_BRONZE9 = '#a18072';
export const WDS_MODALS_BRONZE_BRONZE8 = '#bfa094';
export const WDS_MODALS_BRONZE_BRONZE11 = '#846358';
export const WDS_MODALS_BRONZE_BRONZE5 = '#eaddd7';
export const WDS_MODALS_BRONZE_BRONZE4 = '#f2e8e4';
export const WDS_MODALS_BRONZE_BRONZE2 = '#fdf8f6';
export const WDS_MODALS_BRONZE_BRONZE3 = '#f8f1ee';
export const WDS_MODALS_BRONZE_BRONZE12 = '#43302b';
export const WDS_MODALS_BRONZE_BRONZE7 = '#d1b9b0';
export const WDS_MODALS_BRONZE_BRONZE6 = '#e0cec7';
export const WDS_MODALS_CRIMSON_CRIMSON10 = '#e03177';
export const WDS_MODALS_CRIMSON_CRIMSON6 = '#f4c6db';
export const WDS_MODALS_CRIMSON_CRIMSON9 = '#e93d82';
export const WDS_MODALS_CRIMSON_CRIMSON4 = '#fce5f0';
export const WDS_MODALS_CRIMSON_CRIMSON7 = '#edadc8';
export const WDS_MODALS_CRIMSON_CRIMSON5 = '#f9d8e7';
export const WDS_MODALS_CRIMSON_CRIMSON11 = '#d31e66';
export const WDS_MODALS_CRIMSON_CRIMSON12 = '#3d0d1d';
export const WDS_MODALS_CRIMSON_CRIMSON2 = '#fff7fb';
export const WDS_MODALS_CRIMSON_CRIMSON3 = '#feeff6';
export const WDS_MODALS_CRIMSON_CRIMSON8 = '#e58fb1';
export const WDS_MODALS_CRIMSON_CRIMSON1 = '#fffcfd';
export const WDS_MODALS_PINK_PINK10 = '#d23197';
export const WDS_MODALS_PINK_PINK9 = '#d6409f';
export const WDS_MODALS_PINK_PINK7 = '#ecadd4';
export const WDS_MODALS_PINK_PINK1 = '#fffcfe';
export const WDS_MODALS_PINK_PINK11 = '#cd1d8d';
export const WDS_MODALS_PINK_PINK6 = '#f3c6e2';
export const WDS_MODALS_PINK_PINK8 = '#e38ec3';
export const WDS_MODALS_PINK_PINK5 = '#f9d8ec';
export const WDS_MODALS_PINK_PINK4 = '#fce5f3';
export const WDS_MODALS_PINK_PINK3 = '#feeef8';
export const WDS_MODALS_PINK_PINK12 = '#3b0a2a';
export const WDS_MODALS_PINK_PINK2 = '#fff7fc';
export const WDS_MODALS_PLUM_PLUM10 = '#a43cb4';
export const WDS_MODALS_PLUM_PLUM9 = '#ab4aba';
export const WDS_MODALS_PLUM_PLUM12 = '#340c3b';
export const WDS_MODALS_PLUM_PLUM8 = '#cf91d8';
export const WDS_MODALS_PLUM_PLUM6 = '#ebc8ed';
export const WDS_MODALS_PLUM_PLUM2 = '#fff8ff';
export const WDS_MODALS_PLUM_PLUM5 = '#f3d9f4';
export const WDS_MODALS_PLUM_PLUM11 = '#9c2bad';
export const WDS_MODALS_PLUM_PLUM4 = '#f9e5f9';
export const WDS_MODALS_PLUM_PLUM7 = '#dfafe3';
export const WDS_MODALS_PLUM_PLUM3 = '#fceffc';
export const WDS_MODALS_PLUM_PLUM1 = '#fefcff';
export const WDS_MODALS_PURPLE_PURPLE10 = '#8445bc';
export const WDS_MODALS_PURPLE_PURPLE3 = '#f9f1fe';
export const WDS_MODALS_PURPLE_PURPLE8 = '#be93e4';
export const WDS_MODALS_PURPLE_PURPLE7 = '#d3b4ed';
export const WDS_MODALS_PURPLE_PURPLE4 = '#f3e7fc';
export const WDS_MODALS_PURPLE_PURPLE1 = '#fefcfe';
export const WDS_MODALS_PURPLE_PURPLE6 = '#e3ccf4';
export const WDS_MODALS_PURPLE_PURPLE2 = '#fdfaff';
export const WDS_MODALS_PURPLE_PURPLE12 = '#2b0e44';
export const WDS_MODALS_PURPLE_PURPLE11 = '#793aaf';
export const WDS_MODALS_PURPLE_PURPLE9 = '#8e4ec6';
export const WDS_MODALS_PURPLE_PURPLE5 = '#eddbf9';
export const WDS_MODALS_OVERLAY_WHITE_WHITE10 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE8 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE7 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE5 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE4 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE2 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE3 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE12 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE9 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE11 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE6 = '#ffffff';
export const WDS_MODALS_OVERLAY_WHITE_WHITE1 = '#ffffff';
export const WDS_MODALS_OVERLAY_BLACK_BLACK9 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK8 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK6 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK5 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK4 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK3 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK7 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK12 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK11 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK10 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK2 = '#000000';
export const WDS_MODALS_OVERLAY_BLACK_BLACK1 = '#000000';
export const WDS_THEME_ACCENT_COLOR1 = '#009ec2'; // Background
export const WDS_THEME_ACCENT_COLOR2 = '#00abd1'; // Subtle Background
export const WDS_THEME_ACCENT_COLOR3 = '#00b7e0'; // UI Background
export const WDS_THEME_ACCENT_COLOR4 = '#00c4f0'; // Hover Background
export const WDS_THEME_ACCENT_COLOR5 = '#00d0ff'; // Active UI Background
export const WDS_THEME_ACCENT_COLOR6 = '#0fd3ff'; // Subtle Border
export const WDS_THEME_ACCENT_COLOR7 = '#1fd6ff'; // Strong Border
export const WDS_THEME_ACCENT_COLOR8 = '#2ed9ff'; // Hover Border
export const WDS_THEME_ACCENT_COLOR9 = '#3ddbff'; // Primary
export const WDS_THEME_ACCENT_COLOR10 = '#4ddeff'; // Hover Primary
export const WDS_THEME_ACCENT_COLOR11 = '#eeecf9'; // Subtle Text
export const WDS_THEME_ACCENT_COLOR12 = '#eeecf9'; // Text
export const WDS_THEME_BASE_COLOR10 = '#808080'; // Hover Primary
export const WDS_THEME_BASE_COLOR6 = '#b3bcbd'; // Subtle Border
export const WDS_THEME_BASE_COLOR5 = '#c0c8c9'; // Active UI Background
export const WDS_THEME_BASE_COLOR8 = '#999e9f'; // Hover Border
export const WDS_THEME_BASE_COLOR12 = '#020303'; // Text
export const WDS_THEME_BASE_COLOR3 = '#dde3e4'; // UI Background
export const WDS_THEME_BASE_COLOR9 = '#8a8e8f'; // Primary
export const WDS_THEME_BASE_COLOR7 = '#a4acad'; // Strong Border
export const WDS_THEME_BASE_COLOR4 = '#cfd7d8'; // Hover Background
export const WDS_THEME_BASE_COLOR11 = '#cfd6d5'; // Subtle Text
export const WDS_THEME_BASE_COLOR2 = '#eef1f2'; // Subtle Background
export const WDS_THEME_BASE_COLOR1 = '#fcfdfd'; // Background
export const WDS_THEME_GHOST_COLOR1 = '#fcfdfd'; // Background
export const WDS_THEME_GHOST_COLOR2 = '#eef1f2'; // Subtle Background
export const WDS_THEME_GHOST_COLOR3 = '#e4dddd'; // UI Background
export const WDS_THEME_GHOST_COLOR4 = '#cfd7d8'; // Hover Background
export const WDS_THEME_GHOST_COLOR5 = '#c0c8c9'; // Active UI Background
export const WDS_THEME_GHOST_COLOR6 = '#b3bcbd'; // Subtle Border
export const WDS_THEME_GHOST_COLOR7 = '#a4acad'; // Strong Border
export const WDS_THEME_GHOST_COLOR8 = '#999e9f'; // Hover Border
export const WDS_THEME_GHOST_COLOR9 = '#8a8e8f'; // Primary
export const WDS_THEME_GHOST_COLOR10 = '#808080'; // Hover Primary
export const WDS_THEME_GHOST_COLOR11 = '#cfd6d5'; // Subtle Text
export const WDS_THEME_GHOST_COLOR12 = '#020303'; // Text
export const WDS_THEME_ALIAS_SURFACE_DEFAULT = '#fcfdfd'; // Background
export const WDS_THEME_ALIAS_SURFACE_SUBTLE = '#eef1f2'; // Subtle Background
export const WDS_THEME_ALIAS_SURFACE_UI = '#dde3e4'; // UI Background
export const WDS_THEME_ALIAS_COLOR4 = '#cfd7d8'; // Hover Background
export const WDS_THEME_ALIAS_COLOR5 = '#c0c8c9'; // Active UI Background
export const WDS_THEME_ALIAS_COLOR6 = '#b3bcbd'; // Subtle Border
export const WDS_THEME_ALIAS_COLOR7 = '#a4acad'; // Strong Border
export const WDS_THEME_ALIAS_COLOR8 = '#999e9f'; // Hover Border
export const WDS_THEME_ALIAS_COLOR9 = '#8a8e8f'; // Primary
export const WDS_THEME_ALIAS_COLOR10 = '#808080'; // Hover Primary
export const WDS_THEME_ALIAS_COLOR11 = '#cfd6d5'; // Subtle Text
export const WDS_THEME_ALIAS_COLOR12 = '#020303'; // Text
