/**
 * Do not edit directly, this file was auto-generated.
 */

export const FLDS_TYPOGRAPHY_TYPOGRAPHY_DISPLAY_LARGE_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '44px',
  lineHeight: '105%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_DISPLAY_LARGE_REGULER = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '44px',
  lineHeight: '105%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_DISPLAY_LARGE_MEDIUM = {
  fontFamily: 'Inter',
  fontWeight: 500,
  fontSize: '44px',
  lineHeight: '105%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_DISPLAY_LARGE_SEMIBOLD = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '44px',
  lineHeight: '105%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_DISPLAY_LARGE_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '44px',
  lineHeight: '105%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_DISPLAY_LARGE_EXTRABOLD = {
  fontFamily: 'Inter',
  fontWeight: 800,
  fontSize: '44px',
  lineHeight: '105%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_DISPLAY_LARGE_STRONG = {
  fontFamily: 'Inter',
  fontWeight: 900,
  fontSize: '44px',
  lineHeight: '105%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_DISPLAY_SMALL_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '40px',
  lineHeight: '105%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_DISPLAY_SMALL_REGULAR = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '40px',
  lineHeight: '105%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_DISPLAY_SMALL_MEDIUM = {
  fontFamily: 'Inter',
  fontWeight: 500,
  fontSize: '40px',
  lineHeight: '105%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_DISPLAY_SMALL_SEMIBOLD = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '40px',
  lineHeight: '105%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_DISPLAY_SMALL_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '40px',
  lineHeight: '105%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_DISPLAY_SMALL_EXTRABOLD = {
  fontFamily: 'Inter',
  fontWeight: 800,
  fontSize: '40px',
  lineHeight: '105%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_DISPLAY_SMALL_STRONG = {
  fontFamily: 'Inter',
  fontWeight: 900,
  fontSize: '40px',
  lineHeight: '105%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H1_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '40px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H1_MEDIUM = {
  fontFamily: 'Inter',
  fontWeight: 500,
  fontSize: '40px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H1_SEMIBOLD = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '40px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H1_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '40px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H1_EXTRABOLD = {
  fontFamily: 'Inter',
  fontWeight: 800,
  fontSize: '40px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H1_STRONG = {
  fontFamily: 'Inter',
  fontWeight: 900,
  fontSize: '40px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H2_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '28px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H2_MEDIUM = {
  fontFamily: 'Inter',
  fontWeight: 500,
  fontSize: '28px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H2_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '28px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H2_SEMIBOLD = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '28px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H2_EXTRABOLD = {
  fontFamily: 'Inter',
  fontWeight: 800,
  fontSize: '28px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H2_STRONG = {
  fontFamily: 'Inter',
  fontWeight: 900,
  fontSize: '28px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H3_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '24px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H3_REGULAR = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '24px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H3_MEDIUM = {
  fontFamily: 'Inter',
  fontWeight: 500,
  fontSize: '24px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H3_SEMILBOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '24px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H3_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '24px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H3_STRONG = {
  fontFamily: 'Inter',
  fontWeight: 900,
  fontSize: '24px',
  lineHeight: '115%',
  letterSpacing: '0px',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H4_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '20px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H4_REGULAR = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '20px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H4_MEDIUM = {
  fontFamily: 'Inter',
  fontWeight: 500,
  fontSize: '20px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H4_SEMIBOLD = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '20px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H4_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '20px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H4_STRONG = {
  fontFamily: 'Inter',
  fontWeight: 900,
  fontSize: '20px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H5_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '20px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H5_REGULAR = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '20px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H5_MEDIUM = {
  fontFamily: 'Inter',
  fontWeight: 500,
  fontSize: '20px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H5_SEMIBOLD = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '20px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H5_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '20px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H5_STRONG = {
  fontFamily: 'Inter',
  fontWeight: 900,
  fontSize: '20px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H6_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '16px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H6_REGULAR = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '16px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H6_MEDIUM = {
  fontFamily: 'Inter',
  fontWeight: 500,
  fontSize: '16px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H6_SEMIBOLD = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '16px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H6_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '16px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_H6_STRONG = {
  fontFamily: 'Inter',
  fontWeight: 900,
  fontSize: '16px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_TITLE_PAGE_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '44px',
  lineHeight: '120%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_TITLE_PAGE_REGULAR = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '44px',
  lineHeight: '120%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_TITLE_PAGE_MEDIUM = {
  fontFamily: 'Inter',
  fontWeight: 500,
  fontSize: '44px',
  lineHeight: '120%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_TITLE_PAGE_SEMIBOLD = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '44px',
  lineHeight: '120%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_TITLE_PAGE_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '44px',
  lineHeight: '120%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_TITLE_PAGE_EXTRA_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 800,
  fontSize: '44px',
  lineHeight: '120%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_TITLE_PAGE_STRONG = {
  fontFamily: 'Inter',
  fontWeight: 900,
  fontSize: '44px',
  lineHeight: '120%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_TITLE_HERO_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '44px',
  lineHeight: '120%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_TITLE_HERO_REGULAR = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '44px',
  lineHeight: '120%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_TITLE_HERO_MEDIUM = {
  fontFamily: 'Inter',
  fontWeight: 500,
  fontSize: '44px',
  lineHeight: '120%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_TITLE_HERO_SEMIBOLD = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '44px',
  lineHeight: '120%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_TITLE_HERO_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '44px',
  lineHeight: '120%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_TITLE_HERO_EXTRABOLD = {
  fontFamily: 'Inter',
  fontWeight: 800,
  fontSize: '44px',
  lineHeight: '120%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_TITLE_HERO_STRONG = {
  fontFamily: 'Inter',
  fontWeight: 900,
  fontSize: '44px',
  lineHeight: '120%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_SUBTITLE_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '12px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_SUBTITLE_REGULAR = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '12px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_SUBTITLE_MEDIUM = {
  fontFamily: 'Inter',
  fontWeight: 500,
  fontSize: '12px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_SUBTITLE_SEMIBOLD = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '12px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_SUBTITLE_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '12px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_SUBTITLE_EXTRABOLD = {
  fontFamily: 'Inter',
  fontWeight: 800,
  fontSize: '12px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_HEADING_SUBTITLE_STRONG = {
  fontFamily: 'Inter',
  fontWeight: 900,
  fontSize: '12px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_BODY_SMALL_REGULAR = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '12px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_BODY_SMALL_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '12px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_BODY_SMALL_MEDIUM = {
  fontFamily: 'Inter',
  fontWeight: 500,
  fontSize: '12px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_BODY_SMALL_SEMIBOLD = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '12px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_BODY_SMALL_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '12px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_BODY_SMALL_EXTRABOLD = {
  fontFamily: 'Inter',
  fontWeight: 800,
  fontSize: '12px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_BODY_SMALL_STRONG = {
  fontFamily: 'Inter',
  fontWeight: 900,
  fontSize: '12px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_BODY_LARGE_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '14px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_BODY_LARGE_MEDIUM = {
  fontFamily: 'Inter',
  fontWeight: 500,
  fontSize: '14px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_BODY_LARGE_REGULAR = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '14px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_BODY_LARGE_SEMIBOLD = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '14px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_BODY_LARGE_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '14px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_BODY_LARGE_EXTRABOLD = {
  fontFamily: 'Inter',
  fontWeight: 800,
  fontSize: '14px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_BODY_LARGE_STRONG = {
  fontFamily: 'Inter',
  fontWeight: 900,
  fontSize: '14px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_BODY_LARGE_ITALIC = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '14px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_CODE_LIGHT = {
  fontFamily: 'Roboto Mono',
  fontWeight: 400,
  fontSize: '14px',
  lineHeight: '100%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_CODE_REGULAR = {
  fontFamily: 'Roboto Mono',
  fontWeight: 400,
  fontSize: '14px',
  lineHeight: '100%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_CODE_BOLD = {
  fontFamily: 'Roboto Mono',
  fontWeight: 700,
  fontSize: '14px',
  lineHeight: '100%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_LINK_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '14px',
  lineHeight: '125%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_LINK_REGULAR = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '14px',
  lineHeight: '125%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_PARAGRAPH_LINK_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '14px',
  lineHeight: '125%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_REGULAR_2XS = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '8px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_REGULAR_XS = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '10px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_REGULAR_SM = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '12px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_REGULAR_MD = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '14px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_REGULAR_LG = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '16px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_REGULAR_XL = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '20px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_REGULAR_2XL = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '20px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_REGULAR_3XL = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '28px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_REGULAR_4XL = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '32px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_REGULAR_5XL = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '44px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_REGULAR_6XL = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '44px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_REGULAR_7XL = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '44px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_REGULAR_8XL = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '52px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_BOLD_2XS = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '8px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_BOLD_XS = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '10px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_BOLD_SM = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '12px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_BOLD_MD = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '14px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_BOLD_LG = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '16px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_BOLD_XL = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '20px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_BOLD_2XL = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '20px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_BOLD_3XL = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '28px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_BOLD_4XL = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '32px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_BOLD_5XL = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '44px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_BOLD_6XL = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '44px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_BOLD_7XL = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '44px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_TEXT_BOLD_8XL = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '52px',
  lineHeight: 'auto',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_SMALL_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '10px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_SMALL_REGULAR = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '10px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_SMALL_MEDIUM = {
  fontFamily: 'Inter',
  fontWeight: 500,
  fontSize: '10px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_SMALL_SEMIBOLD = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '10px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_SMALL_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '10px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_SMALL_EXTRABOLD = {
  fontFamily: 'Inter',
  fontWeight: 800,
  fontSize: '10px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_SMALL_STRONG = {
  fontFamily: 'Inter',
  fontWeight: 900,
  fontSize: '10px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_MEDIUM_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '12px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_MEDIUM_REGULAR = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '12px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_MEDIUM_MEDIUM = {
  fontFamily: 'Inter',
  fontWeight: 500,
  fontSize: '12px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_MEDIUM_SEMIBOLD = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '12px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_MEDIUM_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '12px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_MEDIUM_EXTRABOLD = {
  fontFamily: 'Inter',
  fontWeight: 800,
  fontSize: '12px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_MEDIUM_STRONG = {
  fontFamily: 'Inter',
  fontWeight: 900,
  fontSize: '12px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_LARGE_LIGHT = {
  fontFamily: 'Inter',
  fontWeight: 300,
  fontSize: '14px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_LARGE_REGULAR = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: '14px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_LARGE_MEDIUM = {
  fontFamily: 'Inter',
  fontWeight: 500,
  fontSize: '14px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_LARGE_SEMIBOLD = {
  fontFamily: 'Inter',
  fontWeight: 600,
  fontSize: '14px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_LARGE_BOLD = {
  fontFamily: 'Inter',
  fontWeight: 700,
  fontSize: '14px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_LARGE_EXTRABOLD = {
  fontFamily: 'Inter',
  fontWeight: 800,
  fontSize: '14px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_LABEL_LARGE_STRONG = {
  fontFamily: 'Inter',
  fontWeight: 900,
  fontSize: '14px',
  lineHeight: '115%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_UTILITIES_COMPONENT_NOTES_REGULAR = {
  fontFamily: 'Roboto Mono',
  fontWeight: '400',
  fontSize: '16px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
export const FLDS_TYPOGRAPHY_TYPOGRAPHY_UTILITIES_COMPONENT_NOTES_BOLD = {
  fontFamily: 'Roboto Mono',
  fontWeight: '700',
  fontSize: '16px',
  lineHeight: '140%',
  letterSpacing: '0%',
  paragraphSpacing: '0',
  paragraphIndent: '0',
  textDecoration: 'NONE',
  textCase: 'ORIGINAL',
};
